/**
 * ChatInputsBase - All generated input types for Chat
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Chat.json
 *
 * Extend ChatInputs (in parent directory) to add custom fields
 */

// Core imports
import { InputType, Field } from 'type-graphql';
import { GraphQLJSONObject, GraphQLJSON } from 'graphql-type-json';
import { BaseInput } from '@base/graphql/BaseInput.js';

// FieldInput decorators - eliminates repetitive decorator stacking
import { FieldInput } from '@base/graphql/decorators/fields/FieldInput.js';
import { FieldInputEnum } from '@base/graphql/decorators/fields/FieldInputEnum.js';
import { FieldInputJSON } from '@base/graphql/decorators/fields/FieldInputJSON.js';

// Zod imports for JSON schema validation
import { z } from 'zod';

// Validation imports (hardcoded for simplicity) - keeping for backward compatibility
import {
  IsUUID,
  IsOptional,
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray
} from 'class-validator';

// Dynamic imports for entity-specific enums and interfaces
import { ChatStatus, ChatStreamingStatu } from '@db/entities/__generated__/ChatBase.js';

// ═════════════════════════════════════════════════════════════════════════════
// Create Input (no id)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating Chat' })
export class CreateChatInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['llmModelId'];

  @FieldInput(String, { inputType: 'create', description: 'Optional chat description', required: false })
  description?: string;

  @FieldInput(String, { inputType: 'create', description: 'Input: Default LLM model for this chat (ID of LLMModel)', required: true })
  llmModelId!: string;

  @FieldInputEnum(ChatStatus, { inputType: 'create', description: 'Input: Chat status for organization. Required field.', required: true, default: 'active' })
  status!: ChatStatus;

  @FieldInput(String, { inputType: 'create', description: 'Custom system prompt override for this chat', required: false })
  systemPrompt?: string;

  @FieldInput(String, { inputType: 'create', description: 'Input: Chat tags for organization. Max 10 items. Items must be unique.', required: false, array: true })
  tags?: string[];

  @FieldInput(String, { inputType: 'create', description: 'Input: Chat title. Required field. Max 255 characters.', required: true, maxLength: 255 })
  title!: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// Update Input (required id, all fields optional)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for updating Chat' })
export class UpdateChatInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['llmModelId'];

  @Field(() => String, { description: 'ID of Chat to update' })
  id!: string;

  @FieldInput(String, { inputType: 'update', description: 'Optional chat description' })
  description?: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Default LLM model for this chat (ID of LLMModel)', required: true })
  llmModelId?: string;

  @FieldInputEnum(ChatStatus, { inputType: 'update', description: 'Input: Chat status for organization. Required field.', default: 'active' })
  status?: ChatStatus;

  @FieldInput(String, { inputType: 'update', description: 'Custom system prompt override for this chat' })
  systemPrompt?: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Chat tags for organization. Max 10 items. Items must be unique.', array: true })
  tags?: string[];

  @FieldInput(String, { inputType: 'update', description: 'Input: Chat title. Required field. Max 255 characters.', maxLength: 255 })
  title?: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// CreateUpdate Input (optional id for upsert)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating or updating Chat' })
export class CreateUpdateChatInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['llmModelId'];

  @Field(() => String, { nullable: true, description: 'ID for update, omit for create' })
  @IsOptional()
  id?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Optional chat description' })
  description?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Default LLM model for this chat (ID of LLMModel)', required: true })
  llmModelId?: string;

  @FieldInputEnum(ChatStatus, { inputType: 'createUpdate', description: 'Input: Chat status for organization. Required field.', default: 'active' })
  status?: ChatStatus;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Custom system prompt override for this chat' })
  systemPrompt?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Chat tags for organization. Max 10 items. Items must be unique.', array: true })
  tags?: string[];

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Chat title. Required field. Max 255 characters.', maxLength: 255 })
  title?: string;

}
