/**
 * ConnectionInputsBase - All generated input types for Connection
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Connection.json
 *
 * Extend ConnectionInputs (in parent directory) to add custom fields
 */

// Core imports
import { InputType, Field } from 'type-graphql';
import { GraphQLJSONObject, GraphQLJSON } from 'graphql-type-json';
import { BaseInput } from '@base/graphql/BaseInput.js';

// FieldInput decorators - eliminates repetitive decorator stacking
import { FieldInput } from '@base/graphql/decorators/fields/FieldInput.js';
import { FieldInputEnum } from '@base/graphql/decorators/fields/FieldInputEnum.js';
import { FieldInputJSON } from '@base/graphql/decorators/fields/FieldInputJSON.js';

// Zod imports for JSON schema validation
import { z } from 'zod';

// Validation imports (hardcoded for simplicity) - keeping for backward compatibility
import {
  IsUUID,
  IsOptional,
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray
} from 'class-validator';

// Dynamic imports for entity-specific enums and interfaces
import { ConnectionKind } from '@db/entities/__generated__/ConnectionBase.js';
import { ConnectionModelType } from '@db/entities/__generated__/ConnectionBase.js';

// ═════════════════════════════════════════════════════════════════════════════
// Create Input (no id)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating Connection' })
export class CreateConnectionInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = [];

  @FieldInput(String, { inputType: 'create', description: 'Input: API key for the connection. Required field.', required: true })
  apiKey!: string;

  @FieldInput(String, { inputType: 'create', description: 'Input: Base URL for the connection. Required field.', required: true })
  baseUrl!: string;

  @FieldInputJSON(z.any(), { inputType: 'create', description: 'Custom headers for the connection', required: false })
  customHeaders?: Record<string, any>;

  @FieldInputEnum(ConnectionKind, { inputType: 'create', description: 'Input: Connection kind. Required field.', required: true, default: 'OPENAI' })
  kind!: ConnectionKind;

  @FieldInput(String, { inputType: 'create', description: 'Input: Name of the connection. Required field.', required: true })
  name!: string;

  @FieldInput(String, { inputType: 'create', description: 'Provider name for the connection', required: false })
  provider?: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// Update Input (required id, all fields optional)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for updating Connection' })
export class UpdateConnectionInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = [];

  @Field(() => String, { description: 'ID of Connection to update' })
  id!: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: API key for the connection. Required field.' })
  apiKey?: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Base URL for the connection. Required field.' })
  baseUrl?: string;

  @FieldInputJSON(z.any(), { inputType: 'update', description: 'Custom headers for the connection' })
  customHeaders?: Record<string, any>;

  @FieldInputEnum(ConnectionKind, { inputType: 'update', description: 'Input: Connection kind. Required field.', default: 'OPENAI' })
  kind?: ConnectionKind;

  @FieldInput(String, { inputType: 'update', description: 'Input: Name of the connection. Required field.' })
  name?: string;

  @FieldInput(String, { inputType: 'update', description: 'Provider name for the connection' })
  provider?: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// CreateUpdate Input (optional id for upsert)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating or updating Connection' })
export class CreateUpdateConnectionInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = [];

  @Field(() => String, { nullable: true, description: 'ID for update, omit for create' })
  @IsOptional()
  id?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: API key for the connection. Required field.' })
  apiKey?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Base URL for the connection. Required field.' })
  baseUrl?: string;

  @FieldInputJSON(z.any(), { inputType: 'createUpdate', description: 'Custom headers for the connection' })
  customHeaders?: Record<string, any>;

  @FieldInputEnum(ConnectionKind, { inputType: 'createUpdate', description: 'Input: Connection kind. Required field.', default: 'OPENAI' })
  kind?: ConnectionKind;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Name of the connection. Required field.' })
  name?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Provider name for the connection' })
  provider?: string;

}
