/**
 * EmbeddingModelInputsBase - All generated input types for EmbeddingModel
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/EmbeddingModel.json
 *
 * Extend EmbeddingModelInputs (in parent directory) to add custom fields
 */

// Core imports
import { InputType, Field } from 'type-graphql';
import { GraphQLJSONObject, GraphQLJSON } from 'graphql-type-json';
import { BaseInput } from '@base/graphql/BaseInput.js';

// FieldInput decorators - eliminates repetitive decorator stacking
import { FieldInput } from '@base/graphql/decorators/fields/FieldInput.js';
import { FieldInputEnum } from '@base/graphql/decorators/fields/FieldInputEnum.js';
import { FieldInputJSON } from '@base/graphql/decorators/fields/FieldInputJSON.js';

// Zod imports for JSON schema validation
import { z } from 'zod';

// Validation imports (hardcoded for simplicity) - keeping for backward compatibility
import {
  IsUUID,
  IsOptional,
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray
} from 'class-validator';

// Dynamic imports for entity-specific enums and interfaces

// ═════════════════════════════════════════════════════════════════════════════
// Create Input (no id)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating EmbeddingModel' })
export class CreateEmbeddingModelInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['connectionId'];

  @FieldInput(String, { inputType: 'create', description: 'Input: Connection for this LLM model (ID of Connection)', required: true })
  connectionId!: string;

  @FieldInput(Number, { inputType: 'create', description: 'Input: Maximum context length supported by the model. Required field.', required: true })
  contextLength!: number;

  @FieldInput(Boolean, { inputType: 'create', description: 'Indicates if this is the default embedding model', required: false, default: false })
  default?: boolean;

  @FieldInput(Number, { inputType: 'create', description: 'Input: Dimension of the embedding vectors. Required field.', required: true })
  dimension!: number;

  @FieldInput(Number, { inputType: 'create', description: 'Maximum batch size supported by the model', required: false, default: 32 })
  maxBatchSize?: number;

  @FieldInput(String, { inputType: 'create', description: 'Input: Unique identifier for the model. Required field.', required: true })
  modelIdentifier!: string;

  @FieldInput(String, { inputType: 'create', description: 'Optional name for the embedding model', required: false })
  name?: string;

  @FieldInput(String, { inputType: 'create', description: 'Default system prompt for the model', required: false })
  systemPrompt?: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// Update Input (required id, all fields optional)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for updating EmbeddingModel' })
export class UpdateEmbeddingModelInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['connectionId'];

  @Field(() => String, { description: 'ID of EmbeddingModel to update' })
  id!: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Connection for this LLM model (ID of Connection)', required: true })
  connectionId?: string;

  @FieldInput(Number, { inputType: 'update', description: 'Input: Maximum context length supported by the model. Required field.' })
  contextLength?: number;

  @FieldInput(Boolean, { inputType: 'update', description: 'Indicates if this is the default embedding model', default: false })
  default?: boolean;

  @FieldInput(Number, { inputType: 'update', description: 'Input: Dimension of the embedding vectors. Required field.' })
  dimension?: number;

  @FieldInput(Number, { inputType: 'update', description: 'Maximum batch size supported by the model', default: 32 })
  maxBatchSize?: number;

  @FieldInput(String, { inputType: 'update', description: 'Input: Unique identifier for the model. Required field.' })
  modelIdentifier?: string;

  @FieldInput(String, { inputType: 'update', description: 'Optional name for the embedding model' })
  name?: string;

  @FieldInput(String, { inputType: 'update', description: 'Default system prompt for the model' })
  systemPrompt?: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// CreateUpdate Input (optional id for upsert)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating or updating EmbeddingModel' })
export class CreateUpdateEmbeddingModelInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['connectionId'];

  @Field(() => String, { nullable: true, description: 'ID for update, omit for create' })
  @IsOptional()
  id?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Connection for this LLM model (ID of Connection)', required: true })
  connectionId?: string;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Input: Maximum context length supported by the model. Required field.' })
  contextLength?: number;

  @FieldInput(Boolean, { inputType: 'createUpdate', description: 'Indicates if this is the default embedding model', default: false })
  default?: boolean;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Input: Dimension of the embedding vectors. Required field.' })
  dimension?: number;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Maximum batch size supported by the model', default: 32 })
  maxBatchSize?: number;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Unique identifier for the model. Required field.' })
  modelIdentifier?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Optional name for the embedding model' })
  name?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Default system prompt for the model' })
  systemPrompt?: string;

}
