/**
 * FileInputsBase - All generated input types for File
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/File.json
 *
 * Extend FileInputs (in parent directory) to add custom fields
 */

// Core imports
import { InputType, Field } from 'type-graphql';
import { GraphQLJSONObject, GraphQLJSON } from 'graphql-type-json';
import { BaseInput } from '@base/graphql/BaseInput.js';

// FieldInput decorators - eliminates repetitive decorator stacking
import { FieldInput } from '@base/graphql/decorators/fields/FieldInput.js';
import { FieldInputEnum } from '@base/graphql/decorators/fields/FieldInputEnum.js';
import { FieldInputJSON } from '@base/graphql/decorators/fields/FieldInputJSON.js';

// Zod imports for JSON schema validation
import { z } from 'zod';

// Validation imports (hardcoded for simplicity) - keeping for backward compatibility
import {
  IsUUID,
  IsOptional,
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray
} from 'class-validator';

// Dynamic imports for entity-specific enums and interfaces
import { FileStatus, FileFileType } from '@db/entities/__generated__/FileBase.js';

// ═════════════════════════════════════════════════════════════════════════════
// Create Input (no id)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating File' })
export class CreateFileInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = [];

  @FieldInput(String, { inputType: 'create', description: 'Input: File extension (e.g., jpg, png, pdf). Required field. Max 10 characters.', required: true, maxLength: 10 })
  extension!: string;

  @FieldInput(String, { inputType: 'create', description: 'Input: Original filename with extension. Required field. Max 255 characters.', required: true, maxLength: 255 })
  filename!: string;

  @FieldInput(String, { inputType: 'create', description: 'Input: Full file path in local storage. Required field.', required: true })
  fullPath!: string;

  @FieldInput(String, { inputType: 'create', description: 'Reference to the owning entity ID', required: false, maxLength: 36 })
  ownerId?: string;

  @FieldInput(String, { inputType: 'create', description: 'Reference to the owning entity type', required: false })
  ownerType?: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// Update Input (required id, all fields optional)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for updating File' })
export class UpdateFileInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = [];

  @Field(() => String, { description: 'ID of File to update' })
  id!: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: File extension (e.g., jpg, png, pdf). Required field. Max 10 characters.', maxLength: 10 })
  extension?: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Original filename with extension. Required field. Max 255 characters.', maxLength: 255 })
  filename?: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Full file path in local storage. Required field.' })
  fullPath?: string;

  @FieldInput(String, { inputType: 'update', description: 'Reference to the owning entity ID', required: false, maxLength: 36 })
  ownerId?: string;

  @FieldInput(String, { inputType: 'update', description: 'Reference to the owning entity type', required: false })
  ownerType?: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// CreateUpdate Input (optional id for upsert)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating or updating File' })
export class CreateUpdateFileInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = [];

  @Field(() => String, { nullable: true, description: 'ID for update, omit for create' })
  @IsOptional()
  id?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: File extension (e.g., jpg, png, pdf). Required field. Max 10 characters.', maxLength: 10 })
  extension?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Original filename with extension. Required field. Max 255 characters.', maxLength: 255 })
  filename?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Full file path in local storage. Required field.' })
  fullPath?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Reference to the owning entity ID', required: false, maxLength: 36 })
  ownerId?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Reference to the owning entity type', required: false })
  ownerType?: string;

}
