/**
 * JobInputsBase - All generated input types for Job
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Job.json
 *
 * Extend JobInputs (in parent directory) to add custom fields
 */

// Core imports
import { InputType, Field } from 'type-graphql';
import { GraphQLJSONObject, GraphQLJSON } from 'graphql-type-json';
import { BaseInput } from '@base/graphql/BaseInput.js';

// FieldInput decorators - eliminates repetitive decorator stacking
import { FieldInput } from '@base/graphql/decorators/fields/FieldInput.js';
import { FieldInputEnum } from '@base/graphql/decorators/fields/FieldInputEnum.js';
import { FieldInputJSON } from '@base/graphql/decorators/fields/FieldInputJSON.js';

// Zod imports for JSON schema validation
import { z } from 'zod';

// Validation imports (hardcoded for simplicity) - keeping for backward compatibility
import {
  IsUUID,
  IsOptional,
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray
} from 'class-validator';

// Dynamic imports for entity-specific enums and interfaces
import { JobStatus } from '@db/entities/__generated__/JobBase.js';

// ═════════════════════════════════════════════════════════════════════════════
// Create Input (no id)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating Job' })
export class CreateJobInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = [];

  @FieldInput(Date, { inputType: 'create', description: 'When job completed', required: false })
  completedAt?: Date;

  @FieldInput(String, { inputType: 'create', description: 'Deduplication key to prevent duplicate jobs', required: false })
  dedupeKey?: string;

  @FieldInput(String, { inputType: 'create', description: 'Error message if failed', required: false })
  error?: string;

  @FieldInput(Date, { inputType: 'create', description: 'When to retry the job', required: false })
  nextRetryAt?: Date;

  @FieldInputJSON(z.any(), { inputType: 'create', description: 'Input: Job parameters. Required field.', required: true })
  parameters!: Record<string, any>;

  @FieldInput(Number, { inputType: 'create', description: 'Input: Job priority (0-100 scale). Required field.', required: true, default: 0 })
  priority!: number;

  @FieldInput(Date, { inputType: 'create', description: 'When job was queued', required: false })
  queuedAt?: Date;

  @FieldInputJSON(z.any(), { inputType: 'create', description: 'Job execution result', required: false })
  result?: Record<string, any>;

  @FieldInput(Number, { inputType: 'create', description: 'Input: Number of retry attempts. Required field.', required: true, default: 0 })
  retryCount!: number;

  @FieldInput(Date, { inputType: 'create', description: 'When job is scheduled to run', required: false })
  scheduledAt?: Date;

  @FieldInput(Date, { inputType: 'create', description: 'When job started execution', required: false })
  startedAt?: Date;

  @FieldInputEnum(JobStatus, { inputType: 'create', description: 'Input: Job execution status. Required field.', required: true, default: 'PENDING' })
  status!: JobStatus;

  @FieldInput(String, { inputType: 'create', description: 'Input: Target entity ID. Required field.', required: true })
  targetId!: string;

  @FieldInput(Number, { inputType: 'create', description: 'Input: Job timeout in milliseconds. Required field.', required: true, default: 300000 })
  timeoutMS!: number;

  @FieldInput(String, { inputType: 'create', description: 'Input: Job handler type. Required field.', required: true })
  type!: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// Update Input (required id, all fields optional)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for updating Job' })
export class UpdateJobInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = [];

  @Field(() => String, { description: 'ID of Job to update' })
  id!: string;

  @FieldInput(Date, { inputType: 'update', description: 'When job completed' })
  completedAt?: Date;

  @FieldInput(String, { inputType: 'update', description: 'Deduplication key to prevent duplicate jobs' })
  dedupeKey?: string;

  @FieldInput(String, { inputType: 'update', description: 'Error message if failed' })
  error?: string;

  @FieldInput(Date, { inputType: 'update', description: 'When to retry the job' })
  nextRetryAt?: Date;

  @FieldInputJSON(z.any(), { inputType: 'update', description: 'Input: Job parameters. Required field.' })
  parameters?: Record<string, any>;

  @FieldInput(Number, { inputType: 'update', description: 'Input: Job priority (0-100 scale). Required field.', default: 0 })
  priority?: number;

  @FieldInput(Date, { inputType: 'update', description: 'When job was queued' })
  queuedAt?: Date;

  @FieldInputJSON(z.any(), { inputType: 'update', description: 'Job execution result' })
  result?: Record<string, any>;

  @FieldInput(Number, { inputType: 'update', description: 'Input: Number of retry attempts. Required field.', default: 0 })
  retryCount?: number;

  @FieldInput(Date, { inputType: 'update', description: 'When job is scheduled to run' })
  scheduledAt?: Date;

  @FieldInput(Date, { inputType: 'update', description: 'When job started execution' })
  startedAt?: Date;

  @FieldInputEnum(JobStatus, { inputType: 'update', description: 'Input: Job execution status. Required field.', default: 'PENDING' })
  status?: JobStatus;

  @FieldInput(String, { inputType: 'update', description: 'Input: Target entity ID. Required field.' })
  targetId?: string;

  @FieldInput(Number, { inputType: 'update', description: 'Input: Job timeout in milliseconds. Required field.', default: 300000 })
  timeoutMS?: number;

  @FieldInput(String, { inputType: 'update', description: 'Input: Job handler type. Required field.' })
  type?: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// CreateUpdate Input (optional id for upsert)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating or updating Job' })
export class CreateUpdateJobInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = [];

  @Field(() => String, { nullable: true, description: 'ID for update, omit for create' })
  @IsOptional()
  id?: string;

  @FieldInput(Date, { inputType: 'createUpdate', description: 'When job completed' })
  completedAt?: Date;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Deduplication key to prevent duplicate jobs' })
  dedupeKey?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Error message if failed' })
  error?: string;

  @FieldInput(Date, { inputType: 'createUpdate', description: 'When to retry the job' })
  nextRetryAt?: Date;

  @FieldInputJSON(z.any(), { inputType: 'createUpdate', description: 'Input: Job parameters. Required field.' })
  parameters?: Record<string, any>;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Input: Job priority (0-100 scale). Required field.', default: 0 })
  priority?: number;

  @FieldInput(Date, { inputType: 'createUpdate', description: 'When job was queued' })
  queuedAt?: Date;

  @FieldInputJSON(z.any(), { inputType: 'createUpdate', description: 'Job execution result' })
  result?: Record<string, any>;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Input: Number of retry attempts. Required field.', default: 0 })
  retryCount?: number;

  @FieldInput(Date, { inputType: 'createUpdate', description: 'When job is scheduled to run' })
  scheduledAt?: Date;

  @FieldInput(Date, { inputType: 'createUpdate', description: 'When job started execution' })
  startedAt?: Date;

  @FieldInputEnum(JobStatus, { inputType: 'createUpdate', description: 'Input: Job execution status. Required field.', default: 'PENDING' })
  status?: JobStatus;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Target entity ID. Required field.' })
  targetId?: string;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Input: Job timeout in milliseconds. Required field.', default: 300000 })
  timeoutMS?: number;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Job handler type. Required field.' })
  type?: string;

}
