/**
 * LLMModelInputsBase - All generated input types for LLMModel
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/LLMModel.json
 *
 * Extend LLMModelInputs (in parent directory) to add custom fields
 */

// Core imports
import { InputType, Field } from 'type-graphql';
import { GraphQLJSONObject, GraphQLJSON } from 'graphql-type-json';
import { BaseInput } from '@base/graphql/BaseInput.js';

// FieldInput decorators - eliminates repetitive decorator stacking
import { FieldInput } from '@base/graphql/decorators/fields/FieldInput.js';
import { FieldInputEnum } from '@base/graphql/decorators/fields/FieldInputEnum.js';
import { FieldInputJSON } from '@base/graphql/decorators/fields/FieldInputJSON.js';

// Zod imports for JSON schema validation
import { z } from 'zod';

// Validation imports (hardcoded for simplicity) - keeping for backward compatibility
import {
  IsUUID,
  IsOptional,
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray
} from 'class-validator';

// Dynamic imports for entity-specific enums and interfaces
import { LLMModelCapability } from '@db/entities/__generated__/LLMModelBase.js';

// ═════════════════════════════════════════════════════════════════════════════
// Create Input (no id)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating LLMModel' })
export class CreateLLMModelInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['connectionId'];

  @FieldInputEnum(LLMModelCapability, { inputType: 'create', description: 'Input: LLM capability types. Required field.', required: true, array: true })
  capabilities!: LLMModelCapability[];

  @FieldInput(String, { inputType: 'create', description: 'Input: Connection for this LLM model (ID of Connection)', required: true })
  connectionId!: string;

  @FieldInput(Number, { inputType: 'create', description: 'Input: Context length. Required field.', required: true })
  contextLength!: number;

  @FieldInput(Boolean, { inputType: 'create', description: 'Indicates if this is the default llm model', required: false })
  default?: boolean;

  @FieldInput(String, { inputType: 'create', description: 'Input: Unique model identifier. Required field.', required: true })
  modelIdentifier!: string;

  @FieldInput(String, { inputType: 'create', description: 'Name of the model', required: false })
  name?: string;

  @FieldInput(String, { inputType: 'create', description: 'Default system prompt for the model', required: false })
  systemPrompt?: string;

  @FieldInput(Number, { inputType: 'create', description: 'Input: Sampling temperature. Required field.', required: true })
  temperature!: number;

}

// ═════════════════════════════════════════════════════════════════════════════
// Update Input (required id, all fields optional)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for updating LLMModel' })
export class UpdateLLMModelInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['connectionId'];

  @Field(() => String, { description: 'ID of LLMModel to update' })
  id!: string;

  @FieldInputEnum(LLMModelCapability, { inputType: 'update', description: 'Input: LLM capability types. Required field.', array: true })
  capabilities?: LLMModelCapability[];

  @FieldInput(String, { inputType: 'update', description: 'Input: Connection for this LLM model (ID of Connection)', required: false })
  connectionId?: string;

  @FieldInput(Number, { inputType: 'update', description: 'Input: Context length. Required field.' })
  contextLength?: number;

  @FieldInput(Boolean, { inputType: 'update', description: 'Indicates if this is the default llm model' })
  default?: boolean;

  @FieldInput(String, { inputType: 'update', description: 'Input: Unique model identifier. Required field.' })
  modelIdentifier?: string;

  @FieldInput(String, { inputType: 'update', description: 'Name of the model' })
  name?: string;

  @FieldInput(String, { inputType: 'update', description: 'Default system prompt for the model' })
  systemPrompt?: string;

  @FieldInput(Number, { inputType: 'update', description: 'Input: Sampling temperature. Required field.' })
  temperature?: number;

}

// ═════════════════════════════════════════════════════════════════════════════
// CreateUpdate Input (optional id for upsert)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating or updating LLMModel' })
export class CreateUpdateLLMModelInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['connectionId'];

  @Field(() => String, { nullable: true, description: 'ID for update, omit for create' })
  @IsOptional()
  id?: string;

  @FieldInputEnum(LLMModelCapability, { inputType: 'createUpdate', description: 'Input: LLM capability types. Required field.', array: true })
  capabilities?: LLMModelCapability[];

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Connection for this LLM model (ID of Connection)', required: false })
  connectionId?: string;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Input: Context length. Required field.' })
  contextLength?: number;

  @FieldInput(Boolean, { inputType: 'createUpdate', description: 'Indicates if this is the default llm model' })
  default?: boolean;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Unique model identifier. Required field.' })
  modelIdentifier?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Name of the model' })
  name?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Default system prompt for the model' })
  systemPrompt?: string;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Input: Sampling temperature. Required field.' })
  temperature?: number;

}
