/**
 * MessageVersionInputsBase - All generated input types for MessageVersion
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/MessageVersion.json
 *
 * Extend MessageVersionInputs (in parent directory) to add custom fields
 */

// Core imports
import { InputType, Field } from 'type-graphql';
import { GraphQLJSONObject, GraphQLJSON } from 'graphql-type-json';
import { BaseInput } from '@base/graphql/BaseInput.js';

// FieldInput decorators - eliminates repetitive decorator stacking
import { FieldInput } from '@base/graphql/decorators/fields/FieldInput.js';
import { FieldInputEnum } from '@base/graphql/decorators/fields/FieldInputEnum.js';
import { FieldInputJSON } from '@base/graphql/decorators/fields/FieldInputJSON.js';

// Zod imports for JSON schema validation
import { z } from 'zod';

// Validation imports (hardcoded for simplicity) - keeping for backward compatibility
import {
  IsUUID,
  IsOptional,
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray
} from 'class-validator';

// Dynamic imports for entity-specific enums and interfaces
import { MessageVersionStatus } from '@db/entities/__generated__/MessageVersionBase.js';

// ═════════════════════════════════════════════════════════════════════════════
// Create Input (no id)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating MessageVersion' })
export class CreateMessageVersionInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['messageId', 'llmModelId', 'parentVersionId'];

  @FieldInput(String, { inputType: 'create', description: 'Input: Version-specific message content. Required field.', required: true })
  content!: string;

  @FieldInputJSON(z.any(), { inputType: 'create', description: 'Additional metadata about context used for generation (e.g., document sources, summary info)', required: false })
  contextMetadata?: Record<string, any>;

  @FieldInput(Number, { inputType: 'create', description: 'Number of tokens used in conversation context for generation', required: false })
  contextTokens?: number;

  @FieldInput(Number, { inputType: 'create', description: 'Time in milliseconds taken to generate this response', required: false })
  generationTime?: number;

  @FieldInput(Boolean, { inputType: 'create', description: 'Input: Whether this version is a regeneration of an original response. Required field.', required: true, default: false })
  isRegenerated!: boolean;

  @FieldInput(String, { inputType: 'create', description: 'Input: LLM model used to generate this version (ID of LLMModel)', required: true })
  llmModelId!: string;

  @FieldInput(String, { inputType: 'create', description: 'Input: Parent message ID (ID of Message)', required: false })
  messageId?: string;

  @FieldInput(String, { inputType: 'create', description: 'Input: Previous version for regeneration lineage tracking (ID of MessageVersion)', required: false })
  parentVersionId?: string;

  @FieldInputEnum(MessageVersionStatus, { inputType: 'create', description: 'Input: Version status for tracking streaming state. Required field.', required: true, default: 'pending' })
  status!: MessageVersionStatus;

}

// ═════════════════════════════════════════════════════════════════════════════
// Update Input (required id, all fields optional)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for updating MessageVersion' })
export class UpdateMessageVersionInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['messageId', 'llmModelId', 'parentVersionId'];

  @Field(() => String, { description: 'ID of MessageVersion to update' })
  id!: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Version-specific message content. Required field.' })
  content?: string;

  @FieldInputJSON(z.any(), { inputType: 'update', description: 'Additional metadata about context used for generation (e.g., document sources, summary info)' })
  contextMetadata?: Record<string, any>;

  @FieldInput(Number, { inputType: 'update', description: 'Number of tokens used in conversation context for generation' })
  contextTokens?: number;

  @FieldInput(Number, { inputType: 'update', description: 'Time in milliseconds taken to generate this response' })
  generationTime?: number;

  @FieldInput(Boolean, { inputType: 'update', description: 'Input: Whether this version is a regeneration of an original response. Required field.', default: false })
  isRegenerated?: boolean;

  @FieldInput(String, { inputType: 'update', description: 'Input: LLM model used to generate this version (ID of LLMModel)', required: false })
  llmModelId?: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Parent message ID (ID of Message)', required: false })
  messageId?: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Previous version for regeneration lineage tracking (ID of MessageVersion)', required: false })
  parentVersionId?: string;

  @FieldInputEnum(MessageVersionStatus, { inputType: 'update', description: 'Input: Version status for tracking streaming state. Required field.', default: 'pending' })
  status?: MessageVersionStatus;

}

// ═════════════════════════════════════════════════════════════════════════════
// CreateUpdate Input (optional id for upsert)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating or updating MessageVersion' })
export class CreateUpdateMessageVersionInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['messageId', 'llmModelId', 'parentVersionId'];

  @Field(() => String, { nullable: true, description: 'ID for update, omit for create' })
  @IsOptional()
  id?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Version-specific message content. Required field.' })
  content?: string;

  @FieldInputJSON(z.any(), { inputType: 'createUpdate', description: 'Additional metadata about context used for generation (e.g., document sources, summary info)' })
  contextMetadata?: Record<string, any>;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Number of tokens used in conversation context for generation' })
  contextTokens?: number;

  @FieldInput(Number, { inputType: 'createUpdate', description: 'Time in milliseconds taken to generate this response' })
  generationTime?: number;

  @FieldInput(Boolean, { inputType: 'createUpdate', description: 'Input: Whether this version is a regeneration of an original response. Required field.', default: false })
  isRegenerated?: boolean;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: LLM model used to generate this version (ID of LLMModel)', required: false })
  llmModelId?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Parent message ID (ID of Message)', required: false })
  messageId?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Previous version for regeneration lineage tracking (ID of MessageVersion)', required: false })
  parentVersionId?: string;

  @FieldInputEnum(MessageVersionStatus, { inputType: 'createUpdate', description: 'Input: Version status for tracking streaming state. Required field.', default: 'pending' })
  status?: MessageVersionStatus;

}
