/**
 * MessageInputsBase - All generated input types for Message
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Message.json
 *
 * Extend MessageInputs (in parent directory) to add custom fields
 */

// Core imports
import { InputType, Field } from 'type-graphql';
import { GraphQLJSONObject, GraphQLJSON } from 'graphql-type-json';
import { BaseInput } from '@base/graphql/BaseInput.js';

// FieldInput decorators - eliminates repetitive decorator stacking
import { FieldInput } from '@base/graphql/decorators/fields/FieldInput.js';
import { FieldInputEnum } from '@base/graphql/decorators/fields/FieldInputEnum.js';
import { FieldInputJSON } from '@base/graphql/decorators/fields/FieldInputJSON.js';

// Zod imports for JSON schema validation
import { z } from 'zod';

// Validation imports (hardcoded for simplicity) - keeping for backward compatibility
import {
  IsUUID,
  IsOptional,
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray
} from 'class-validator';

// Dynamic imports for entity-specific enums and interfaces
import { MessageRole } from '@db/entities/__generated__/MessageBase.js';

// ═════════════════════════════════════════════════════════════════════════════
// Create Input (no id)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating Message' })
export class CreateMessageInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['chatId', 'currentVersionId', 'llmModelId'];

  @FieldInput(String, { inputType: 'create', description: 'Input: Parent chat ID (ID of Chat)', required: true })
  chatId!: string;

  @FieldInput(String, { inputType: 'create', description: 'Input: Current version of the message (ID of MessageVersion)', required: true })
  currentVersionId!: string;

  @FieldInput(String, { inputType: 'create', description: 'Input: LLM model ID used for this message (for user messages) (ID of LLMModel)', required: false })
  llmModelId?: string;

  @FieldInputEnum(MessageRole, { inputType: 'create', description: 'Input: Message role in conversation. Required field.', required: true })
  role!: MessageRole;

}

// ═════════════════════════════════════════════════════════════════════════════
// Update Input (required id, all fields optional)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for updating Message' })
export class UpdateMessageInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['chatId', 'currentVersionId', 'llmModelId'];

  @Field(() => String, { description: 'ID of Message to update' })
  id!: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Parent chat ID (ID of Chat)', required: false })
  chatId?: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: Current version of the message (ID of MessageVersion)', required: false })
  currentVersionId?: string;

  @FieldInput(String, { inputType: 'update', description: 'Input: LLM model ID used for this message (for user messages) (ID of LLMModel)', required: false })
  llmModelId?: string;

  @FieldInputEnum(MessageRole, { inputType: 'update', description: 'Input: Message role in conversation. Required field.' })
  role?: MessageRole;

}

// ═════════════════════════════════════════════════════════════════════════════
// CreateUpdate Input (optional id for upsert)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating or updating Message' })
export class CreateUpdateMessageInputBase extends BaseInput {
  // Fields that contain foreign key IDs (converted from Relay global IDs to local IDs)
  static relationFields = ['chatId', 'currentVersionId', 'llmModelId'];

  @Field(() => String, { nullable: true, description: 'ID for update, omit for create' })
  @IsOptional()
  id?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Parent chat ID (ID of Chat)', required: false })
  chatId?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: Current version of the message (ID of MessageVersion)', required: false })
  currentVersionId?: string;

  @FieldInput(String, { inputType: 'createUpdate', description: 'Input: LLM model ID used for this message (for user messages) (ID of LLMModel)', required: false })
  llmModelId?: string;

  @FieldInputEnum(MessageRole, { inputType: 'createUpdate', description: 'Input: Message role in conversation. Required field.' })
  role?: MessageRole;

}
