/**
 * UserInputsBase - All generated input types for User
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/User.json
 *
 * Extend UserInputs (in parent directory) to add custom fields
 */

import { InputType, Field } from 'type-graphql';
import { GraphQLJSONObject, GraphQLJSON } from 'graphql-type-json';
import { BaseInput } from '@base/graphql/BaseInput.js';
import { IsUUID, IsOptional, IsString, Matches, MaxLength, MinLength } from 'class-validator';

// ═════════════════════════════════════════════════════════════════════════════
// Create Input (no id)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating User' })
export class CreateUserInputBase extends BaseInput {
  @Field(() => String, { description: 'User name' })
  @IsString()
  @MinLength(1)
  @MaxLength(255)
  name!: string;

  @Field(() => String, { description: 'Unique username' })
  @IsString()
  @MinLength(3)
  @MaxLength(100)
  @Matches(/^[a-zA-Z0-9_-]+$/)
  username!: string;

  @Field(() => String, { description: 'User password' })
  @IsString()
  @MinLength(8)
  password!: string;

  @Field(() => String, { description: 'Session key for user authentication', nullable: true })
  @IsOptional()
  @IsString()
  sessionKey?: string;
}

// ═════════════════════════════════════════════════════════════════════════════
// Update Input (required id, all fields optional)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for updating User' })
export class UpdateUserInputBase extends BaseInput {
  @Field(() => String, { description: 'ID of User to update' })
  id!: string;

  @Field(() => String, { description: 'User name', nullable: true })
  @IsOptional()
  @IsString()
  @MinLength(1)
  @MaxLength(255)
  name?: string;

  @Field(() => String, { description: 'Unique username', nullable: true })
  @IsOptional()
  @IsString()
  @MinLength(3)
  @MaxLength(100)
  @Matches(/^[a-zA-Z0-9_-]+$/)
  username?: string;

  @Field(() => String, { description: 'User password', nullable: true })
  @IsOptional()
  @IsString()
  @MinLength(8)
  password?: string;

  @Field(() => String, { description: 'Session key for user authentication', nullable: true })
  @IsOptional()
  @IsString()
  sessionKey?: string;

}

// ═════════════════════════════════════════════════════════════════════════════
// CreateUpdate Input (optional id for upsert)
// ═════════════════════════════════════════════════════════════════════════════

@InputType({ description: 'Input for creating or updating User' })
export class CreateUpdateUserInputBase extends BaseInput {
  @Field(() => String, { nullable: true, description: 'ID for update, omit for create' })
  @IsOptional()
  id?: string;

  @Field(() => String, { description: 'User name' })
  @IsString()
  @MinLength(1)
  @MaxLength(255)
  name!: string;

  @Field(() => String, { description: 'Unique username' })
  @IsString()
  @MinLength(3)
  @MaxLength(100)
  @Matches(/^[a-zA-Z0-9_-]+$/)
  username!: string;

  @Field(() => String, { description: 'User password' })
  @IsString()
  @MinLength(8)
  password!: string;

  @Field(() => String, { description: 'Session key for user authentication', nullable: true })
  @IsOptional()
  @IsString()
  sessionKey?: string;

}
