/**
 * ChatBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Chat.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/Chat.ts (extends this class)
 * 2. Modify schemas/Chat.json and run: yarn graphql
 */

/**
 * Chat Entity Schema
 * Chat conversation entity for managing AI conversations
 *
 * ## Base Fields (inherited from OwnedEntity)
 * @property string id - UUID primary key
 * @property string userId - Owner ID (authenticated)
 * @property Date createdAt - Auto-generated timestamp
 * @property Date updatedAt - Auto-updated timestamp
 * @property Date deletedAt - Soft delete support
 *
 * ## Fields
 * @property string | null description - Optional chat description
 * @property ChatStatus status - Chat status for organization - default: active, enum: [active, archived, deleted]
 * @property ChatStreamingStatu streamingStatus - Streaming status of the chat - default: idle, enum: [idle, streaming]
 * @property string | null systemPrompt - Custom system prompt override for this chat
 * @property string[][] | null tags - Chat tags for organization
 * @property string title - Chat title - max: 255
 *
 * ## Relationships
 * @property LLMModel llmModel - LLMModel (eager-loaded)
 *
 * ## Database Indexes
 * @property {SingleIndex} llmModel
 * @property {SingleIndex} status
 * @property {SingleIndex} updatedAt
 * @property {CompositeIndex} [status, updatedAt]
 */

// Core imports
import { ObjectType, Field, ID, registerEnumType } from 'type-graphql';
import { Entity, Column, Index, ManyToOne, OneToMany, ManyToMany, OneToOne, JoinColumn, RelationId, ObjectLiteral } from 'typeorm';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';

// Validation imports
import {
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsUUID,
  IsOptional,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray,
  IsNotEmptyObject,
  IsDefined
} from 'class-validator';

// Base entity
import { OwnedEntity } from '@base/db/OwnedEntity.js';
import { DataSourceProvider } from '@base/db/index.js';

// Dynamic entity imports (if any relationships exist)
import { LLMModel } from '../LLMModel.js';

// ──────────────────────────────────────────────────────────────────────────
// Enum Definitions
// ──────────────────────────────────────────────────────────────────────────

export enum ChatStatus {
  active = 'active',
  archived = 'archived',
  deleted = 'deleted'
}

export enum ChatStreamingStatu {
  idle = 'idle',
  streaming = 'streaming'
}


// ──────────────────────────────────────────────────────────────────────────
// JSON Interface Definitions
// ──────────────────────────────────────────────────────────────────────────


// ──────────────────────────────────────────────────────────────────────────
// Zod Schema Definitions for JSON Array Items
// ──────────────────────────────────────────────────────────────────────────

const ChatTagsSchema = z.array(z.string().max(25)).min(0).max(10).describe('ChatTagsSchema: Array of strings');


@ObjectType()
export abstract class ChatBase extends OwnedEntity {
  @FieldColumn(String, { required: false, description: 'Optional chat description' })
  description?: string;

  @Field(() => ID, { description: 'Default LLM model for this chat' })
  @FieldColumn(String, { required: true, description: 'Default LLM model for this chat (Foreign key for llmModel)' })
  llmModelId!: string;

  @FieldColumnEnum(ChatStatus, { description: 'Chat status for organization', defaultValue: ChatStatus.active })
  status!: ChatStatus;

  @FieldColumnEnum(ChatStreamingStatu, { description: 'Streaming status of the chat', defaultValue: ChatStreamingStatu.idle })
  streamingStatus!: ChatStreamingStatu;

  @FieldColumn(String, { required: false, description: 'Custom system prompt override for this chat' })
  systemPrompt?: string;

  @FieldColumnJSON(ChatTagsSchema, { description: 'Chat tags for organization', nullable: true })
  tags?: string[];

  @FieldColumn(String, { required: true, description: 'Chat title', maxLength: 255 })
  title!: string;

  // ──────────────────────────────────────────────────────────────────────────
  // Relationships
  // ──────────────────────────────────────────────────────────────────────────

  @Field(() => LLMModel, { description: 'Default LLM model for this chat', nullable: false })
  @ManyToOne(() => LLMModel, { eager: true })
  @JoinColumn({ name: 'llmModelId' })
  @ValidateNested()
  llmModel!: LLMModel;

}
