/**
 * ConnectionBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Connection.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/Connection.ts (extends this class)
 * 2. Modify schemas/Connection.json and run: yarn graphql
 */

/**
 * Connection Entity Schema
 * Connection entity
 *
 * ## Base Fields (inherited from OwnedEntity)
 * @property string id - UUID primary key
 * @property string userId - Owner ID (authenticated)
 * @property Date createdAt - Auto-generated timestamp
 * @property Date updatedAt - Auto-updated timestamp
 * @property Date deletedAt - Soft delete support
 *
 * ## Fields
 * @property string apiKey - API key for the connection
 * @property string baseUrl - Base URL for the connection
 * @property Record&lt;string, any&gt; | null customHeaders - Custom headers for the connection
 * @property ConnectionKind kind - Connection kind - default: OPENAI, enum: [OPENAI, ANTHROPIC]
 * @property Record&lt;string, any&gt;[][] | null models - AI models used in creating or analyzing this post
 * @property string name - Name of the connection
 * @property string | null provider - Provider name for the connection
 *
 * ## Database Indexes
 * @property {SingleIndex} userId
 */

// Core imports
import { ObjectType, Field, ID, registerEnumType } from 'type-graphql';
import { Entity, Column, Index, ManyToOne, OneToMany, ManyToMany, OneToOne, JoinColumn, RelationId, ObjectLiteral } from 'typeorm';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';

// Validation imports
import {
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsUUID,
  IsOptional,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray,
  IsNotEmptyObject,
  IsDefined
} from 'class-validator';

// Base entity
import { OwnedEntity } from '@base/db/OwnedEntity.js';
import { DataSourceProvider } from '@base/db/index.js';

// Dynamic entity imports (if any relationships exist)

// ──────────────────────────────────────────────────────────────────────────
// Enum Definitions
// ──────────────────────────────────────────────────────────────────────────

export enum ConnectionKind {
  OPENAI = 'OPENAI',
  ANTHROPIC = 'ANTHROPIC'
}


// ──────────────────────────────────────────────────────────────────────────
// JSON Interface Definitions
// ──────────────────────────────────────────────────────────────────────────

export interface ConnectionModelType {
  id: string;
  name: string;
  version: string;
  provider: string;
}


// ──────────────────────────────────────────────────────────────────────────
// Zod Schema Definitions for JSON Array Items
// ──────────────────────────────────────────────────────────────────────────

const ConnectionModelTypeSchema = z.object({
  id: z.string(),
  name: z.string(),
  version: z.string(),
  provider: z.string(),
}).describe('ConnectionModelType: Generated schema');

const ConnectionModelsSchema = z.array(ConnectionModelTypeSchema).describe('ConnectionModelsSchema: Array of ConnectionModelType');


@ObjectType()
export abstract class ConnectionBase extends OwnedEntity {
  @FieldColumn(String, { required: true, description: 'API key for the connection' })
  apiKey!: string;

  @FieldColumn(String, { required: true, description: 'Base URL for the connection' })
  baseUrl!: string;

  @FieldColumnJSON(z.any(), { description: 'Custom headers for the connection', nullable: true })
  customHeaders?: Record<string, any>;

  @FieldColumnEnum(ConnectionKind, { description: 'Connection kind', defaultValue: ConnectionKind.OPENAI })
  kind!: ConnectionKind;

  @FieldColumnJSON(ConnectionModelsSchema, { description: 'AI models used in creating or analyzing this post', nullable: true })
  models?: ConnectionModelType[];

  @FieldColumn(String, { required: true, description: 'Name of the connection' })
  name!: string;

  @FieldColumn(String, { required: false, description: 'Provider name for the connection' })
  provider?: string;

}
