/**
 * EmbeddingModelBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/EmbeddingModel.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/EmbeddingModel.ts (extends this class)
 * 2. Modify schemas/EmbeddingModel.json and run: yarn graphql
 */

/**
 * EmbeddingModel Entity Schema
 * Embedding model entity
 *
 * ## Base Fields (inherited from OwnedEntity)
 * @property string id - UUID primary key
 * @property string userId - Owner ID (authenticated)
 * @property Date createdAt - Auto-generated timestamp
 * @property Date updatedAt - Auto-updated timestamp
 * @property Date deletedAt - Soft delete support
 *
 * ## Fields
 * @property number contextLength - Maximum context length supported by the model
 * @property boolean | null default - Indicates if this is the default embedding model - default: false
 * @property number dimension - Dimension of the embedding vectors
 * @property number | null maxBatchSize - Maximum batch size supported by the model - default: 32
 * @property string modelIdentifier - Unique identifier for the model
 * @property string | null name - Optional name for the embedding model
 * @property string | null systemPrompt - Default system prompt for the model
 *
 * ## Relationships
 * @property Connection connection - Connection (eager-loaded)
 *
 * ## Database Indexes
 * @property {SingleIndex} userId
 * @property {SingleIndex} connectionId
 */

// Core imports
import { ObjectType, Field, ID, registerEnumType } from 'type-graphql';
import { Entity, Column, Index, ManyToOne, OneToMany, ManyToMany, OneToOne, JoinColumn, RelationId, ObjectLiteral } from 'typeorm';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';

// Validation imports
import {
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsUUID,
  IsOptional,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray,
  IsNotEmptyObject,
  IsDefined
} from 'class-validator';

// Base entity
import { OwnedEntity } from '@base/db/OwnedEntity.js';
import { DataSourceProvider } from '@base/db/index.js';

// Dynamic entity imports (if any relationships exist)
import { Connection } from '../Connection.js';




@ObjectType()
export abstract class EmbeddingModelBase extends OwnedEntity {
  @Field(() => ID, { description: 'Connection for this LLM model' })
  @FieldColumn(String, { required: true, description: 'Connection for this LLM model (Foreign key for connection)' })
  connectionId!: string;

  @FieldColumn(Number, { required: true, description: 'Maximum context length supported by the model' })
  contextLength!: number;

  @FieldColumn(Boolean, { required: false, description: 'Indicates if this is the default embedding model', defaultValue: false })
  default?: boolean;

  @FieldColumn(Number, { required: true, description: 'Dimension of the embedding vectors' })
  dimension!: number;

  @FieldColumn(Number, { required: false, description: 'Maximum batch size supported by the model', defaultValue: 32 })
  maxBatchSize?: number;

  @FieldColumn(String, { required: true, description: 'Unique identifier for the model' })
  modelIdentifier!: string;

  @FieldColumn(String, { required: false, description: 'Optional name for the embedding model' })
  name?: string;

  @FieldColumn(String, { required: false, description: 'Default system prompt for the model' })
  systemPrompt?: string;

  // ──────────────────────────────────────────────────────────────────────────
  // Relationships
  // ──────────────────────────────────────────────────────────────────────────

  @Field(() => Connection, { description: 'Connection for this LLM model', nullable: false })
  @ManyToOne(() => Connection, { eager: true })
  @JoinColumn({ name: 'connectionId' })
  @ValidateNested()
  connection!: Connection;

}
