/**
 * FileBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/File.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/File.ts (extends this class)
 * 2. Modify schemas/File.json and run: yarn graphql
 */

/**
 * File Entity Schema
 * File entity for storing file references with AI-generated descriptions
 *
 * ## Base Fields (inherited from OwnedEntity)
 * @property string id - UUID primary key
 * @property string userId - Owner ID (authenticated)
 * @property Date createdAt - Auto-generated timestamp
 * @property Date updatedAt - Auto-updated timestamp
 * @property Date deletedAt - Soft delete support
 *
 * ## Fields
 * @property string extension - File extension (e.g., jpg, png, pdf) - max: 10
 * @property string fileHash - SHA-256 hash for deduplication and integrity - default: &lt;empty&gt;
 * @property string filename - Original filename with extension - max: 255
 * @property number fileSize - File size in bytes - default: 0
 * @property FileFileType fileType - File type category - default: other, enum: [image, document, audio, video, other]
 * @property string fullPath - Full file path in local storage
 * @property Record&lt;string, any&gt; | null metadata - Additional file metadata (dimensions, EXIF data, etc.)
 * @property string mimeType - MIME type of the file - default: application/octet-stream
 * @property number mkTime - File system modification time - default: 0
 * @property FileStatus status - File processing status - default: pending, enum: [pending, error, processing, completed]
 *
 * ## Polymorphic Relations
 * @property {string | null} ownerId - Foreign key ID
 * @property {string | null} ownerType - Target entity type
 * @property {Promise<any | null>} owner - Polymorphic getter method
 *
 * ## Database Indexes
 * @property {SingleIndex} fileHash
 * @property {SingleIndex} fileType
 * @property {CompositeIndex} [fileType, createdAt]
 */

// Core imports
import { ObjectType, Field, ID, registerEnumType } from 'type-graphql';
import { Entity, Column, Index, ManyToOne, OneToMany, ManyToMany, OneToOne, JoinColumn, RelationId, ObjectLiteral } from 'typeorm';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';

// Validation imports
import {
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsUUID,
  IsOptional,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray,
  IsNotEmptyObject,
  IsDefined
} from 'class-validator';

// Base entity
import { OwnedEntity } from '@base/db/OwnedEntity.js';
import { DataSourceProvider } from '@base/db/index.js';

// Dynamic entity imports (if any relationships exist)

// ──────────────────────────────────────────────────────────────────────────
// Enum Definitions
// ──────────────────────────────────────────────────────────────────────────

export enum FileStatus {
  pending = 'pending',
  error = 'error',
  processing = 'processing',
  completed = 'completed'
}

export enum FileFileType {
  image = 'image',
  document = 'document',
  audio = 'audio',
  video = 'video',
  other = 'other'
}




@ObjectType()
export abstract class FileBase extends OwnedEntity {
  @FieldColumn(String, { required: true, description: 'File extension (e.g., jpg, png, pdf)', maxLength: 10 })
  extension!: string;

  @FieldColumn(String, { required: true, description: 'SHA-256 hash for deduplication and integrity', defaultValue: '<empty>' })
  fileHash!: string;

  @FieldColumn(String, { required: true, description: 'Original filename with extension', maxLength: 255 })
  filename!: string;

  @FieldColumn(Number, { required: true, description: 'File size in bytes', defaultValue: 0 })
  fileSize!: number;

  @FieldColumnEnum(FileFileType, { description: 'File type category', defaultValue: FileFileType.other })
  fileType!: FileFileType;

  @FieldColumn(String, { required: true, description: 'Full file path in local storage' })
  fullPath!: string;

  @FieldColumnJSON(z.any(), { description: 'Additional file metadata (dimensions, EXIF data, etc.)', nullable: true })
  metadata?: Record<string, any>;

  @FieldColumn(String, { required: true, description: 'MIME type of the file', defaultValue: 'application/octet-stream' })
  mimeType!: string;

  @FieldColumn(Number, { required: true, description: 'File system modification time', defaultValue: 0 })
  mkTime!: number;

  @FieldColumnEnum(FileStatus, { description: 'File processing status', defaultValue: FileStatus.pending })
  status!: FileStatus;

  @FieldColumn(String, { required: false, description: 'Reference to the owning entity ID', maxLength: 36 })
  ownerId?: string;

  @FieldColumn(String, { required: false, description: 'Reference to the owning entity type' })
  ownerType?: string;

  // ──────────────────────────────────────────────────────────────────────────
  // Polymorphic Methods
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Gets the polymorphic owner entity
   */
  async getOwner<T extends ObjectLiteral>(): Promise<T | null> {
    if (!this.ownerId || !this.ownerType) {
      return null;
    }

    // Get repository dynamically from TypeORM
    const dataSource = DataSourceProvider.get();
    const repository = dataSource.getRepository(this.ownerType);

    return await repository.findOne({ where: { id: this.ownerId } }) as T | null;
  }

}
