/**
 * JobBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Job.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/Job.ts (extends this class)
 * 2. Modify schemas/Job.json and run: yarn graphql
 */

/**
 * Job Entity Schema
 * Background job for async task execution
 *
 * ## Base Fields (inherited from OwnedEntity)
 * @property string id - UUID primary key
 * @property string userId - Owner ID (authenticated)
 * @property Date createdAt - Auto-generated timestamp
 * @property Date updatedAt - Auto-updated timestamp
 * @property Date deletedAt - Soft delete support
 *
 * ## Fields
 * @property Date | null completedAt - When job completed
 * @property string | null dedupeKey - Deduplication key to prevent duplicate jobs
 * @property string | null error - Error message if failed
 * @property Date | null nextRetryAt - When to retry the job
 * @property Record&lt;string, any&gt; parameters - Job parameters
 * @property number priority - Job priority (0-100 scale) - default: 0
 * @property Date | null queuedAt - When job was queued
 * @property Record&lt;string, any&gt; | null result - Job execution result
 * @property number retryCount - Number of retry attempts - default: 0
 * @property Date | null scheduledAt - When job is scheduled to run
 * @property Date | null startedAt - When job started execution
 * @property JobStatus status - Job execution status - default: PENDING, enum: [PENDING, RUNNING, COMPLETED, POSTPONED, FAILED]
 * @property string targetId - Target entity ID
 * @property number timeoutMS - Job timeout in milliseconds - default: 300000
 * @property string type - Job handler type
 *
 * ## Database Indexes
 * @property {SingleIndex} userId
 * @property {CompositeIndex} [status, type]
 * @property {CompositeIndex} [targetId, type]
 * @property {SingleIndex} nextRetryAt
 * @property {SingleIndex} scheduledAt
 * @property {CompositeIndex} [status, queuedAt]
 * @property {SingleIndex} dedupeKey
 */

// Core imports
import { ObjectType, Field, ID, registerEnumType } from 'type-graphql';
import { Entity, Column, Index, ManyToOne, OneToMany, ManyToMany, OneToOne, JoinColumn, RelationId, ObjectLiteral } from 'typeorm';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';

// Validation imports
import {
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsUUID,
  IsOptional,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray,
  IsNotEmptyObject,
  IsDefined
} from 'class-validator';

// Base entity
import { OwnedEntity } from '@base/db/OwnedEntity.js';
import { DataSourceProvider } from '@base/db/index.js';

// Dynamic entity imports (if any relationships exist)

// ──────────────────────────────────────────────────────────────────────────
// Enum Definitions
// ──────────────────────────────────────────────────────────────────────────

export enum JobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  POSTPONED = 'POSTPONED',
  FAILED = 'FAILED'
}




@ObjectType()
export abstract class JobBase extends OwnedEntity {
  @FieldColumn(Date, { required: false, description: 'When job completed' })
  completedAt?: Date;

  @FieldColumn(String, { required: false, description: 'Deduplication key to prevent duplicate jobs' })
  dedupeKey?: string;

  @FieldColumn(String, { required: false, description: 'Error message if failed' })
  error?: string;

  @FieldColumn(Date, { required: false, description: 'When to retry the job' })
  nextRetryAt?: Date;

  @FieldColumnJSON(z.any(), { description: 'Job parameters' })
  parameters!: Record<string, any>;

  @FieldColumn(Number, { required: true, description: 'Job priority (0-100 scale)', defaultValue: 0 })
  priority!: number;

  @FieldColumn(Date, { required: false, description: 'When job was queued' })
  queuedAt?: Date;

  @FieldColumnJSON(z.any(), { description: 'Job execution result', nullable: true })
  result?: Record<string, any>;

  @FieldColumn(Number, { required: true, description: 'Number of retry attempts', defaultValue: 0 })
  retryCount!: number;

  @FieldColumn(Date, { required: false, description: 'When job is scheduled to run' })
  scheduledAt?: Date;

  @FieldColumn(Date, { required: false, description: 'When job started execution' })
  startedAt?: Date;

  @FieldColumnEnum(JobStatus, { description: 'Job execution status', defaultValue: JobStatus.PENDING })
  status!: JobStatus;

  @FieldColumn(String, { required: true, description: 'Target entity ID' })
  targetId!: string;

  @FieldColumn(Number, { required: true, description: 'Job timeout in milliseconds', defaultValue: 300000 })
  timeoutMS!: number;

  @FieldColumn(String, { required: true, description: 'Job handler type' })
  type!: string;

}
