/**
 * LLMModelBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/LLMModel.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/LLMModel.ts (extends this class)
 * 2. Modify schemas/LLMModel.json and run: yarn graphql
 */

/**
 * LLMModel Entity Schema
 * LLM Model entity
 *
 * ## Base Fields (inherited from OwnedEntity)
 * @property string id - UUID primary key
 * @property string userId - Owner ID (authenticated)
 * @property Date createdAt - Auto-generated timestamp
 * @property Date updatedAt - Auto-updated timestamp
 * @property Date deletedAt - Soft delete support
 *
 * ## Fields
 * @property LLMModelCapability[][] capabilities - LLM capability types - enum: [TEXT, VISION]
 * @property number contextLength - Context length
 * @property boolean | null default - Indicates if this is the default llm model
 * @property string modelIdentifier - Unique model identifier
 * @property string | null name - Name of the model
 * @property string | null systemPrompt - Default system prompt for the model
 * @property number temperature - Sampling temperature
 *
 * ## Relationships
 * @property Connection connection - Connection (eager-loaded)
 *
 * ## Database Indexes
 * @property {SingleIndex} connectionId
 */

// Core imports
import { ObjectType, Field, ID, registerEnumType } from 'type-graphql';
import { Entity, Column, Index, ManyToOne, OneToMany, ManyToMany, OneToOne, JoinColumn, RelationId, ObjectLiteral } from 'typeorm';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';

// Validation imports
import {
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsUUID,
  IsOptional,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray,
  IsNotEmptyObject,
  IsDefined
} from 'class-validator';

// Base entity
import { OwnedEntity } from '@base/db/OwnedEntity.js';
import { DataSourceProvider } from '@base/db/index.js';

// Dynamic entity imports (if any relationships exist)
import { Connection } from '../Connection.js';

// ──────────────────────────────────────────────────────────────────────────
// Enum Definitions
// ──────────────────────────────────────────────────────────────────────────

export enum LLMModelCapability {
  TEXT = 'TEXT',
  VISION = 'VISION'
}




@ObjectType()
export abstract class LLMModelBase extends OwnedEntity {
  @FieldColumnEnum(LLMModelCapability, { description: 'LLM capability types', array: true })
  capabilities!: LLMModelCapability[];

  @Field(() => ID, { description: 'Connection for this LLM model' })
  @FieldColumn(String, { required: true, description: 'Connection for this LLM model (Foreign key for connection)' })
  connectionId!: string;

  @FieldColumn(Number, { required: true, description: 'Context length' })
  contextLength!: number;

  @FieldColumn(Boolean, { required: false, description: 'Indicates if this is the default llm model' })
  default?: boolean;

  @FieldColumn(String, { required: true, description: 'Unique model identifier' })
  modelIdentifier!: string;

  @FieldColumn(String, { required: false, description: 'Name of the model' })
  name?: string;

  @FieldColumn(String, { required: false, description: 'Default system prompt for the model' })
  systemPrompt?: string;

  @FieldColumn(Number, { required: true, description: 'Sampling temperature' })
  temperature!: number;

  // ──────────────────────────────────────────────────────────────────────────
  // Relationships
  // ──────────────────────────────────────────────────────────────────────────

  @Field(() => Connection, { description: 'Connection for this LLM model', nullable: false })
  @ManyToOne(() => Connection, { eager: true })
  @JoinColumn({ name: 'connectionId' })
  @ValidateNested()
  connection!: Connection;

}
