/**
 * MessageBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Message.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/Message.ts (extends this class)
 * 2. Modify schemas/Message.json and run: yarn graphql
 */

/**
 * Message Entity Schema
 * Message entity for individual chat messages with versioning support
 *
 * ## Base Fields (inherited from OwnedEntity)
 * @property string id - UUID primary key
 * @property string userId - Owner ID (authenticated)
 * @property Date createdAt - Auto-generated timestamp
 * @property Date updatedAt - Auto-updated timestamp
 * @property Date deletedAt - Soft delete support
 *
 * ## Fields
 * @property MessageRole role - Message role in conversation - enum: [user, assistant, system]
 *
 * ## Relationships
 * @property Promise&lt;Chat&gt; chat - Chat (lazy-loaded)
 * @property Promise&lt;MessageVersion&gt; currentVersion - MessageVersion (lazy-loaded)
 * @property Promise&lt;LLMModel | null&gt; llmModel - LLMModel (lazy-loaded)
 *
 * ## Database Indexes
 * @property {SingleIndex} chatId
 * @property {SingleIndex} createdAt
 * @property {CompositeIndex} [chatId, createdAt]
 */

// Core imports
import { ObjectType, Field, ID, registerEnumType } from 'type-graphql';
import { Entity, Column, Index, ManyToOne, OneToMany, ManyToMany, OneToOne, JoinColumn, RelationId, ObjectLiteral } from 'typeorm';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';

// Validation imports
import {
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsUUID,
  IsOptional,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray,
  IsNotEmptyObject,
  IsDefined
} from 'class-validator';

// Base entity
import { OwnedEntity } from '@base/db/OwnedEntity.js';
import { DataSourceProvider } from '@base/db/index.js';

// Dynamic entity imports (if any relationships exist)
import { Chat } from '../Chat.js';
import { MessageVersion } from '../MessageVersion.js';
import { LLMModel } from '../LLMModel.js';

// ──────────────────────────────────────────────────────────────────────────
// Enum Definitions
// ──────────────────────────────────────────────────────────────────────────

export enum MessageRole {
  user = 'user',
  assistant = 'assistant',
  system = 'system'
}




@ObjectType()
export abstract class MessageBase extends OwnedEntity {
  @Field(() => ID, { description: 'Parent chat ID' })
  @FieldColumn(String, { required: true, description: 'Parent chat ID (Foreign key for chat)' })
  chatId!: string;

  @Field(() => ID, { description: 'Current version of the message' })
  @FieldColumn(String, { required: true, description: 'Current version of the message (Foreign key for currentVersion)' })
  currentVersionId!: string;

  @Field(() => ID, { description: 'LLM model ID used for this message (for user messages)' })
  @FieldColumn(String, { required: false, description: 'LLM model ID used for this message (for user messages) (Foreign key for llmModel)' })
  llmModelId?: string;

  @FieldColumnEnum(MessageRole, { description: 'Message role in conversation' })
  role!: MessageRole;

  // ──────────────────────────────────────────────────────────────────────────
  // Relationships
  // ──────────────────────────────────────────────────────────────────────────

  @Field(() => Chat, { description: 'Parent chat ID', nullable: false })
  @ManyToOne(() => Chat, { onDelete: "CASCADE", onUpdate: "CASCADE" })
  @JoinColumn({ name: 'chatId' })
  @ValidateNested()
  chat!: Promise<Chat>;

  @Field(() => MessageVersion, { description: 'Current version of the message', nullable: false })
  @OneToOne(() => MessageVersion)
  @JoinColumn({ name: 'currentVersionId' })
  @ValidateNested()
  currentVersion!: Promise<MessageVersion>;

  @Field(() => LLMModel, { description: 'LLM model ID used for this message (for user messages)', nullable: true })
  @ManyToOne(() => LLMModel)
  @JoinColumn({ name: 'llmModelId' })
  @IsOptional()
  @ValidateNested()
  llmModel?: Promise<LLMModel | null>;

}
