/**
 * MessageVersionBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/MessageVersion.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/MessageVersion.ts (extends this class)
 * 2. Modify schemas/MessageVersion.json and run: yarn graphql
 */

/**
 * MessageVersion Entity Schema
 * Message version entity for supporting response regeneration and version comparison
 *
 * ## Base Fields (inherited from OwnedEntity)
 * @property string id - UUID primary key
 * @property string userId - Owner ID (authenticated)
 * @property Date createdAt - Auto-generated timestamp
 * @property Date updatedAt - Auto-updated timestamp
 * @property Date deletedAt - Soft delete support
 *
 * ## Fields
 * @property string content - Version-specific message content
 * @property Record&lt;string, any&gt; | null contextMetadata - Additional metadata about context used for generation (e.g., document sources, summary info)
 * @property number | null contextTokens - Number of tokens used in conversation context for generation
 * @property number | null generationTime - Time in milliseconds taken to generate this response
 * @property boolean isRegenerated - Whether this version is a regeneration of an original response - default: false
 * @property MessageVersionStatus status - Version status for tracking streaming state - default: pending, enum: [pending, streaming, completed, failed, cancelled]
 *
 * ## Relationships
 * @property Promise&lt;LLMModel&gt; llmModel - LLMModel (lazy-loaded)
 * @property Promise&lt;Message | null&gt; message - Message (lazy-loaded)
 * @property Promise&lt;MessageVersion | null&gt; parentVersion - MessageVersion (lazy-loaded)
 *
 * ## Database Indexes
 * @property {SingleIndex} messageId
 * @property {SingleIndex} llmModelId
 * @property {SingleIndex} createdAt
 * @property {CompositeIndex} [messageId, createdAt]
 * @property {CompositeIndex} [llmModelId, createdAt]
 */

// Core imports
import { ObjectType, Field, ID, registerEnumType } from 'type-graphql';
import { Entity, Column, Index, ManyToOne, OneToMany, ManyToMany, OneToOne, JoinColumn, RelationId, ObjectLiteral } from 'typeorm';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';

// Validation imports
import {
  IsString,
  IsNumber,
  IsBoolean,
  IsDate,
  IsUUID,
  IsOptional,
  IsNotEmpty,
  MinLength,
  MaxLength,
  Min,
  Max,
  Matches,
  IsEnum,
  IsObject,
  IsUrl,
  IsEmail,
  ValidateNested,
  ArrayMinSize,
  ArrayMaxSize,
  IsArray,
  IsNotEmptyObject,
  IsDefined
} from 'class-validator';

// Base entity
import { OwnedEntity } from '@base/db/OwnedEntity.js';
import { DataSourceProvider } from '@base/db/index.js';

// Dynamic entity imports (if any relationships exist)
import { Message } from '../Message.js';
import { LLMModel } from '../LLMModel.js';
import { MessageVersion } from '../MessageVersion.js';

// ──────────────────────────────────────────────────────────────────────────
// Enum Definitions
// ──────────────────────────────────────────────────────────────────────────

export enum MessageVersionStatus {
  pending = 'pending',
  streaming = 'streaming',
  completed = 'completed',
  failed = 'failed',
  cancelled = 'cancelled'
}




@ObjectType()
export abstract class MessageVersionBase extends OwnedEntity {
  @FieldColumn(String, { required: true, description: 'Version-specific message content' })
  content!: string;

  @FieldColumnJSON(z.any(), { description: 'Additional metadata about context used for generation (e.g., document sources, summary info)', nullable: true })
  contextMetadata?: Record<string, any>;

  @FieldColumn(Number, { required: false, description: 'Number of tokens used in conversation context for generation' })
  contextTokens?: number;

  @FieldColumn(Number, { required: false, description: 'Time in milliseconds taken to generate this response' })
  generationTime?: number;

  @FieldColumn(Boolean, { required: true, description: 'Whether this version is a regeneration of an original response', defaultValue: false })
  isRegenerated!: boolean;

  @Field(() => ID, { description: 'LLM model used to generate this version' })
  @FieldColumn(String, { required: true, description: 'LLM model used to generate this version (Foreign key for llmModel)' })
  llmModelId!: string;

  @Field(() => ID, { description: 'Parent message ID' })
  @FieldColumn(String, { required: false, description: 'Parent message ID (Foreign key for message)' })
  messageId?: string;

  @Field(() => ID, { description: 'Previous version for regeneration lineage tracking' })
  @FieldColumn(String, { required: false, description: 'Previous version for regeneration lineage tracking (Foreign key for parentVersion)' })
  parentVersionId?: string;

  @FieldColumnEnum(MessageVersionStatus, { description: 'Version status for tracking streaming state', defaultValue: MessageVersionStatus.pending })
  status!: MessageVersionStatus;

  // ──────────────────────────────────────────────────────────────────────────
  // Relationships
  // ──────────────────────────────────────────────────────────────────────────

  @Field(() => LLMModel, { description: 'LLM model used to generate this version', nullable: false })
  @ManyToOne(() => LLMModel)
  @JoinColumn({ name: 'llmModelId' })
  @ValidateNested()
  llmModel!: Promise<LLMModel>;

  @Field(() => Message, { description: 'Parent message ID', nullable: true })
  @ManyToOne(() => Message)
  @JoinColumn({ name: 'messageId' })
  @IsOptional()
  @ValidateNested()
  message?: Promise<Message | null>;

  @Field(() => MessageVersion, { description: 'Previous version for regeneration lineage tracking', nullable: true })
  @ManyToOne(() => MessageVersion)
  @JoinColumn({ name: 'parentVersionId' })
  @IsOptional()
  @ValidateNested()
  parentVersion?: Promise<MessageVersion | null>;

}
