/**
 * TestEntityBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/TestEntity.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/TestEntity.ts (extends this class)
 * 2. Modify schemas/TestEntity.json and run: yarn graphql
 *
 */

import { ObjectType, Field } from 'type-graphql';
import { Entity, Column, Index } from 'typeorm';
import { BaseEntity } from '@base/db/index.js';
import { IsOptional, IsString } from 'class-validator';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';
import { OwnedEntity } from '@base/db/OwnedEntity.js';




@ObjectType()
export abstract class TestEntityBase extends OwnedEntity {
  @FieldColumn(String, { required: true })
  name!: string;

  @FieldColumn(String, { required: false, array: true })
  tags?: string[];

}
