/**
 * TaskBase - Generated base entity class
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Task.json
 *
 * To customize this entity:
 * 1. Edit main/db/entities/Task.ts (extends this class)
 * 2. Modify schemas/Task.json and run: yarn graphql
 *
 */

import { ObjectType, Field, registerEnumType } from 'type-graphql';
import { Entity, Column, Index } from 'typeorm';
import { BaseEntity } from '@base/db/index.js';
import { IsOptional, IsString } from 'class-validator';
import { GraphQLJSONObject } from 'graphql-type-json';
import { z } from 'zod';
import { FieldColumnEnum, FieldColumn, FieldColumnJSON } from '@main/base/graphql/decorators/index.js';
import { OwnedEntity } from '@base/db/OwnedEntity.js';

// ──────────────────────────────────────────────────────────────────────────
// Enum Definitions
// ──────────────────────────────────────────────────────────────────────────

export enum TaskPriority {
  low = 'low',
  medium = 'medium',
  high = 'high'
}




@ObjectType()
export abstract class TaskBase extends OwnedEntity {
  @FieldColumn(String, { required: true })
  title!: string;

  @FieldColumnEnum(TaskPriority, { nullable: true, isArray: true })
  priorities?: TaskPriority[];

}
