/**
 * ChatResolver - Generated GraphQL resolver
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Chat.json
 *
 * To customize:
 * 1. Extend this class in main/graphql/resolvers/ChatResolver.ts
 * 2. Override methods as needed
 *
 */

import { Resolver, Query, Mutation, Arg, Ctx, Args, ObjectType } from 'type-graphql';
import { IsNull } from 'typeorm';
import { Chat } from '@db/entities/Chat.js';
import { CreateChatInput } from '@main/graphql/inputs/ChatInputs.js';
import { UpdateChatInput } from '@main/graphql/inputs/ChatInputs.js';
import type { GraphQLContext } from '@shared/types';
import { connectionFromArray, RelayRepository, fromGlobalIdToLocalId, FieldMutation, CustomRepository } from '@base/graphql/index.js';
import { createConnectionType, ConnectionArgs } from '@base/graphql/relay/Connection.js';
import { BaseResolver } from '@base/graphql/BaseResolver.js';

@ObjectType()
export class ChatConnection extends createConnectionType('Chat', Chat) { }

@Resolver(() => Chat)
export class ChatResolverBase extends BaseResolver {
  protected getRepository(ctx: GraphQLContext): CustomRepository<Chat> {
    // Entity has userId field - use ownership-aware repository with context
    return this.getOwnedRepository(Chat, ctx);
  }

  protected get repository(): RelayRepository<Chat> {
    // This getter is for backward compatibility - use getRepository(ctx) in new methods
    throw new Error('Use getRepository(ctx) instead of this.repository to provide user context');
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Fetch single Chat by ID
   */
  @Query(() => Chat, { nullable: true, description: 'Fetch Chat by ID' })
  async chat(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<Chat | null> {
    return await this.getRepository(ctx).findOne({ where: { id: id } });
  }

  /**
   * Fetch Chat collection (Relay connection)
   */
  @Query(() => ChatConnection, { description: 'Fetch Chat collection (paginated)' })
  async chats(
    @Args(() => ConnectionArgs) args: ConnectionArgs,
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<ReturnType<typeof connectionFromArray<Chat>>> {
    const where = kind === 'default' ? { deletedAt: IsNull() } : {};
    const [items, totalCount] = await this.getRepository(ctx).findAndCount({ where });
    return connectionFromArray(items, args, totalCount);
  }

  /**
   * Fetch Chat array (non-paginated)
   */
  @Query(() => [Chat], { description: 'Fetch Chat array' })
  async chatsArray(
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<Chat[]> {
    if (kind === 'all') {
      return await this.getRepository(ctx).find({ withDeleted: true });
    }
    return await this.getRepository(ctx).find();
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Create new Chat
   */
  @FieldMutation(CreateChatInput, Chat, {
    description: 'Create new Chat'
  })
  async createChat(
    input: CreateChatInput,
    ctx: GraphQLContext
  ): Promise<Chat> {
    const entity = this.getRepository(ctx).create(input);
    // Auto-attach userId directly to entity (preserve constructor)
    if (ctx.user) {
      (entity).userId = ctx.user?.id;
    }
    return await this.getRepository(ctx).save(entity);
  }



  /**
   * Soft delete Chat
   */
  @Mutation(() => Boolean, { description: 'Soft delete Chat' })
  async destroyChat(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    // Use the repository's softDeleteById method which handles ownership and already-deleted entities
    await this.getRepository(ctx).softDeleteById(id);
    return true;
  }

  /**
   * Hard delete Chat
   */
  @Mutation(() => Boolean, { description: 'Hard delete Chat (permanent)' })
  async deleteChat(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: id } });


    await this.getRepository(ctx).hardDeleteById(id);
    return true;
  }

  /**
   * Restore soft-deleted Chat
   */
  @Mutation(() => Chat, { nullable: true, description: 'Restore soft-deleted Chat' })
  async restoreChat(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<Chat | null> {
    const entity = await this.getRepository(ctx).findOne({
      where: { id: id },
      withDeleted: true
    });

    if (!entity || !entity.deletedAt) {
      return null;
    }


    return await this.getRepository(ctx).recoverById(id);
  }
}
