/**
 * ConnectionResolver - Generated GraphQL resolver
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Connection.json
 *
 * To customize:
 * 1. Extend this class in main/graphql/resolvers/ConnectionResolver.ts
 * 2. Override methods as needed
 *
 */

import { Resolver, Query, Mutation, Arg, Ctx, Args, ObjectType } from 'type-graphql';
import { IsNull } from 'typeorm';
import { Connection } from '@db/entities/Connection.js';
import { CreateConnectionInput } from '@main/graphql/inputs/ConnectionInputs.js';
import { CreateUpdateConnectionInput } from '@main/graphql/inputs/ConnectionInputs.js';
import { UpdateConnectionInput } from '@main/graphql/inputs/ConnectionInputs.js';
import type { GraphQLContext } from '@shared/types';
import { connectionFromArray, RelayRepository, fromGlobalIdToLocalId } from '@base/graphql/index.js';
import { createConnectionType, ConnectionArgs } from '@base/graphql/relay/Connection.js';
import { BaseResolver } from '@base/graphql/BaseResolver.js';

@ObjectType()
export class ConnectionConnection extends createConnectionType('Connection', Connection) { }

@Resolver(() => Connection)
export class ConnectionResolverBase extends BaseResolver {
  protected getRepository(ctx: GraphQLContext): RelayRepository<Connection> {
    // Entity has userId field - use ownership-aware repository with context
    return this.getRelayRepository(Connection, ctx);
  }

  protected get repository(): RelayRepository<Connection> {
    // This getter is for backward compatibility - use getRepository(ctx) in new methods
    throw new Error('Use getRepository(ctx) instead of this.repository to provide user context');
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Fetch single Connection by ID
   */
  @Query(() => Connection, { nullable: true, description: 'Fetch Connection by ID' })
  async connection(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<Connection | null> {
    const localId = fromGlobalIdToLocalId(id);
    return await this.getRepository(ctx).findOne({ where: { id: localId } });
  }

  /**
   * Fetch Connection collection (Relay connection)
   */
  @Query(() => ConnectionConnection, { description: 'Fetch Connection collection (paginated)' })
  async connections(
    @Args(() => ConnectionArgs) args: ConnectionArgs,
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<ReturnType<typeof connectionFromArray<Connection>>> {
    const where = kind === 'default' ? { deletedAt: IsNull() } : {};
    const [items, totalCount] = await this.getRepository(ctx).findAndCount({ where });
    return connectionFromArray(items, args, totalCount);
  }

  /**
   * Fetch Connection array (non-paginated)
   */
  @Query(() => [Connection], { description: 'Fetch Connection array' })
  async connectionsArray(
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<Connection[]> {
    if (kind === 'all') {
      return await this.getRepository(ctx).find({ withDeleted: true });
    }
    return await this.getRepository(ctx).find();
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Create new Connection
   */
  @Mutation(() => Connection, { description: 'Create new Connection' })
  async createConnection(
    @Arg('input', () => CreateConnectionInput) input: CreateConnectionInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<Connection> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    const entity = this.getRepository(ctx).create(input as any);
    // Auto-attach userId directly to entity (preserve constructor)
    (entity as any).userId = ctx.user?.id;
    return await this.getRepository(ctx).save(entity as any);
  }

  /**
   * Update existing Connection
   */
  @Mutation(() => Connection, { description: 'Update existing Connection' })
  async updateConnection(
    @Arg('input', () => UpdateConnectionInput) input: UpdateConnectionInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<Connection> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: fromGlobalIdToLocalId(input.id) } });

    // Safely assign only defined, updatable fields (excludes id, userId and undefined values)
    this.safeAssignUpdate(entity, input);
    return await this.getRepository(ctx).save(entity as any);
  }

  /**
   * Create or update Connection (upsert)
   */
  @Mutation(() => Connection, { description: 'Create or update Connection' })
  async createUpdateConnection(
    @Arg('input', () => CreateUpdateConnectionInput) input: CreateUpdateConnectionInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<Connection> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    if (input.id) {
      // Update existing
      const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: fromGlobalIdToLocalId(input.id) } });

      // Safely assign only defined, updatable fields (excludes id, userId and undefined values)
      this.safeAssignUpdate(entity, input);
      return await this.getRepository(ctx).save(entity as any);
    } else {
      // Create new
      const { id, ...createData } = input;
      const entity = this.getRepository(ctx).create(createData as any);
      // Auto-attach userId directly to entity (preserve constructor)
      (entity as any).userId = ctx.user?.id;
      return await this.getRepository(ctx).save(entity as any);
    }
  }

  /**
   * Soft delete Connection
   */
  @Mutation(() => Boolean, { description: 'Soft delete Connection' })
  async destroyConnection(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    // Use the repository's softDeleteById method which handles ownership and already-deleted entities
    const localId = fromGlobalIdToLocalId(id);
    await this.getRepository(ctx).softDeleteById(localId);
    return true;
  }

  /**
   * Hard delete Connection
   */
  @Mutation(() => Boolean, { description: 'Hard delete Connection (permanent)' })
  async deleteConnection(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: localId } });


    await this.getRepository(ctx).hardDeleteById(localId);
    return true;
  }

  /**
   * Restore soft-deleted Connection
   */
  @Mutation(() => Connection, { nullable: true, description: 'Restore soft-deleted Connection' })
  async restoreConnection(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<Connection | null> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOne({
      where: { id: localId },
      withDeleted: true
    });

    if (!entity || !entity.deletedAt) {
      return null;
    }


    return await this.getRepository(ctx).recoverById(localId);
  }
}
