/**
 * EmbeddingModelResolver - Generated GraphQL resolver
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/EmbeddingModel.json
 *
 * To customize:
 * 1. Extend this class in main/graphql/resolvers/EmbeddingModelResolver.ts
 * 2. Override methods as needed
 *
 */

import { Resolver, Query, Mutation, Arg, Ctx, Args, ObjectType } from 'type-graphql';
import { IsNull } from 'typeorm';
import { EmbeddingModel } from '@db/entities/EmbeddingModel.js';
import { CreateEmbeddingModelInput } from '@main/graphql/inputs/EmbeddingModelInputs.js';
import { CreateUpdateEmbeddingModelInput } from '@main/graphql/inputs/EmbeddingModelInputs.js';
import { UpdateEmbeddingModelInput } from '@main/graphql/inputs/EmbeddingModelInputs.js';
import type { GraphQLContext } from '@shared/types';
import { connectionFromArray, RelayRepository, fromGlobalIdToLocalId } from '@base/graphql/index.js';
import { createConnectionType, ConnectionArgs } from '@base/graphql/relay/Connection.js';
import { BaseResolver } from '@base/graphql/BaseResolver.js';

@ObjectType()
export class EmbeddingModelConnection extends createConnectionType('EmbeddingModel', EmbeddingModel) { }

@Resolver(() => EmbeddingModel)
export class EmbeddingModelResolverBase extends BaseResolver {
  protected getRepository(ctx: GraphQLContext): RelayRepository<EmbeddingModel> {
    // Entity has userId field - use ownership-aware repository with context
    return this.getRelayRepository(EmbeddingModel, ctx);
  }

  protected get repository(): RelayRepository<EmbeddingModel> {
    // This getter is for backward compatibility - use getRepository(ctx) in new methods
    throw new Error('Use getRepository(ctx) instead of this.repository to provide user context');
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Fetch single EmbeddingModel by ID
   */
  @Query(() => EmbeddingModel, { nullable: true, description: 'Fetch EmbeddingModel by ID' })
  async embeddingModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<EmbeddingModel | null> {
    const localId = fromGlobalIdToLocalId(id);
    return await this.getRepository(ctx).findOne({ where: { id: localId } });
  }

  /**
   * Fetch EmbeddingModel collection (Relay connection)
   */
  @Query(() => EmbeddingModelConnection, { description: 'Fetch EmbeddingModel collection (paginated)' })
  async embeddingModels(
    @Args(() => ConnectionArgs) args: ConnectionArgs,
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<ReturnType<typeof connectionFromArray<EmbeddingModel>>> {
    const where = kind === 'default' ? { deletedAt: IsNull() } : {};
    const [items, totalCount] = await this.getRepository(ctx).findAndCount({ where });
    return connectionFromArray(items, args, totalCount);
  }

  /**
   * Fetch EmbeddingModel array (non-paginated)
   */
  @Query(() => [EmbeddingModel], { description: 'Fetch EmbeddingModel array' })
  async embeddingModelsArray(
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<EmbeddingModel[]> {
    if (kind === 'all') {
      return await this.getRepository(ctx).find({ withDeleted: true });
    }
    return await this.getRepository(ctx).find();
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Create new EmbeddingModel
   */
  @Mutation(() => EmbeddingModel, { description: 'Create new EmbeddingModel' })
  async createEmbeddingModel(
    @Arg('input', () => CreateEmbeddingModelInput) input: CreateEmbeddingModelInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<EmbeddingModel> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    const entity = this.getRepository(ctx).create(input as any);
    // Auto-attach userId directly to entity (preserve constructor)
    (entity as any).userId = ctx.user?.id;
    return await this.getRepository(ctx).save(entity as any);
  }

  /**
   * Update existing EmbeddingModel
   */
  @Mutation(() => EmbeddingModel, { description: 'Update existing EmbeddingModel' })
  async updateEmbeddingModel(
    @Arg('input', () => UpdateEmbeddingModelInput) input: UpdateEmbeddingModelInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<EmbeddingModel> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: fromGlobalIdToLocalId(input.id) } });

    // Safely assign only defined, updatable fields (excludes id, userId and undefined values)
    this.safeAssignUpdate(entity, input);
    return await this.getRepository(ctx).save(entity as any);
  }

  /**
   * Create or update EmbeddingModel (upsert)
   */
  @Mutation(() => EmbeddingModel, { description: 'Create or update EmbeddingModel' })
  async createUpdateEmbeddingModel(
    @Arg('input', () => CreateUpdateEmbeddingModelInput) input: CreateUpdateEmbeddingModelInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<EmbeddingModel> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    if (input.id) {
      // Update existing
      const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: fromGlobalIdToLocalId(input.id) } });

      // Safely assign only defined, updatable fields (excludes id, userId and undefined values)
      this.safeAssignUpdate(entity, input);
      return await this.getRepository(ctx).save(entity as any);
    } else {
      // Create new
      const { id, ...createData } = input;
      const entity = this.getRepository(ctx).create(createData as any);
      // Auto-attach userId directly to entity (preserve constructor)
      (entity as any).userId = ctx.user?.id;
      return await this.getRepository(ctx).save(entity as any);
    }
  }

  /**
   * Soft delete EmbeddingModel
   */
  @Mutation(() => Boolean, { description: 'Soft delete EmbeddingModel' })
  async destroyEmbeddingModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    // Use the repository's softDeleteById method which handles ownership and already-deleted entities
    const localId = fromGlobalIdToLocalId(id);
    await this.getRepository(ctx).softDeleteById(localId);
    return true;
  }

  /**
   * Hard delete EmbeddingModel
   */
  @Mutation(() => Boolean, { description: 'Hard delete EmbeddingModel (permanent)' })
  async deleteEmbeddingModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: localId } });


    await this.getRepository(ctx).hardDeleteById(localId);
    return true;
  }

  /**
   * Restore soft-deleted EmbeddingModel
   */
  @Mutation(() => EmbeddingModel, { nullable: true, description: 'Restore soft-deleted EmbeddingModel' })
  async restoreEmbeddingModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<EmbeddingModel | null> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOne({
      where: { id: localId },
      withDeleted: true
    });

    if (!entity || !entity.deletedAt) {
      return null;
    }


    return await this.getRepository(ctx).recoverById(localId);
  }
}
