/**
 * FileEntityResolver - Generated GraphQL resolver
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/FileEntity.json
 *
 * To customize:
 * 1. Extend this class in main/graphql/resolvers/FileEntityResolver.ts
 * 2. Override methods as needed
 *
 */

import { Resolver, Query, Mutation, Arg, Ctx, Args, ObjectType } from 'type-graphql';
import { IsNull } from 'typeorm';
import { FileEntity } from '@db/entities/FileEntity.js';
import { CreateFileEntityInput } from '@main/graphql/inputs/FileEntityInputs.js';
import { UpdateFileEntityInput } from '@main/graphql/inputs/FileEntityInputs.js';
import type { GraphQLContext } from '@shared/types';
import { connectionFromArray, RelayRepository, fromGlobalIdToLocalId, FieldMutation, CustomRepository } from '@base/graphql/index.js';
import { createConnectionType, ConnectionArgs } from '@base/graphql/relay/Connection.js';
import { BaseResolver } from '@base/graphql/BaseResolver.js';

@ObjectType()
export class FileEntityConnection extends createConnectionType('FileEntity', FileEntity) { }

@Resolver(() => FileEntity)
export class FileEntityResolverBase extends BaseResolver {
  protected getRepository(ctx: GraphQLContext): CustomRepository<FileEntity> {
    // Entity has userId field - use ownership-aware repository with context
    return this.getOwnedRepository(FileEntity, ctx);
  }

  protected get repository(): RelayRepository<FileEntity> {
    // This getter is for backward compatibility - use getRepository(ctx) in new methods
    throw new Error('Use getRepository(ctx) instead of this.repository to provide user context');
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Fetch single FileEntity by ID
   */
  @Query(() => FileEntity, { nullable: true, description: 'Fetch FileEntity by ID' })
  async fileEntity(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<FileEntity | null> {
    return await this.getRepository(ctx).findOne({ where: { id: id } });
  }

  /**
   * Fetch FileEntity collection (Relay connection)
   */
  @Query(() => FileEntityConnection, { description: 'Fetch FileEntity collection (paginated)' })
  async fileEntities(
    @Args(() => ConnectionArgs) args: ConnectionArgs,
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<ReturnType<typeof connectionFromArray<FileEntity>>> {
    const where = kind === 'default' ? { deletedAt: IsNull() } : {};
    const [items, totalCount] = await this.getRepository(ctx).findAndCount({ where });
    return connectionFromArray(items, args, totalCount);
  }

  /**
   * Fetch FileEntity array (non-paginated)
   */
  @Query(() => [FileEntity], { description: 'Fetch FileEntity array' })
  async fileEntitiesArray(
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<FileEntity[]> {
    if (kind === 'all') {
      return await this.getRepository(ctx).find({ withDeleted: true });
    }
    return await this.getRepository(ctx).find();
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Create new FileEntity
   */
  @FieldMutation(CreateFileEntityInput, FileEntity, {
    description: 'Create new FileEntity'
  })
  async createFileEntity(
    input: CreateFileEntityInput,
    ctx: GraphQLContext
  ): Promise<FileEntity> {
    const entity = this.getRepository(ctx).create(input);
    // Auto-attach userId directly to entity (preserve constructor)
    if (ctx.user) {
      (entity).userId = ctx.user?.id;
    }
    return await this.getRepository(ctx).save(entity);
  }



  /**
   * Soft delete FileEntity
   */
  @Mutation(() => Boolean, { description: 'Soft delete FileEntity' })
  async destroyFileEntity(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    // Use the repository's softDeleteById method which handles ownership and already-deleted entities
    await this.getRepository(ctx).softDeleteById(id);
    return true;
  }

  /**
   * Hard delete FileEntity
   */
  @Mutation(() => Boolean, { description: 'Hard delete FileEntity (permanent)' })
  async deleteFileEntity(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: id } });


    await this.getRepository(ctx).hardDeleteById(id);
    return true;
  }

  /**
   * Restore soft-deleted FileEntity
   */
  @Mutation(() => FileEntity, { nullable: true, description: 'Restore soft-deleted FileEntity' })
  async restoreFileEntity(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<FileEntity | null> {
    const entity = await this.getRepository(ctx).findOne({
      where: { id: id },
      withDeleted: true
    });

    if (!entity || !entity.deletedAt) {
      return null;
    }


    return await this.getRepository(ctx).recoverById(id);
  }
}
