/**
 * LLMModelResolver - Generated GraphQL resolver
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/LLMModel.json
 *
 * To customize:
 * 1. Extend this class in main/graphql/resolvers/LLMModelResolver.ts
 * 2. Override methods as needed
 *
 */

import { Resolver, Query, Mutation, Arg, Ctx, Args, ObjectType } from 'type-graphql';
import { IsNull } from 'typeorm';
import { LLMModel } from '@db/entities/LLMModel.js';
import { CreateLLMModelInput } from '@main/graphql/inputs/LLMModelInputs.js';
import { CreateUpdateLLMModelInput } from '@main/graphql/inputs/LLMModelInputs.js';
import { UpdateLLMModelInput } from '@main/graphql/inputs/LLMModelInputs.js';
import type { GraphQLContext } from '@shared/types';
import { connectionFromArray, RelayRepository, fromGlobalIdToLocalId, FieldMutation, CustomRepository } from '@base/graphql/index.js';
import { createConnectionType, ConnectionArgs } from '@base/graphql/relay/Connection.js';
import { BaseResolver } from '@base/graphql/BaseResolver.js';

@ObjectType()
export class LLMModelConnection extends createConnectionType('LLMModel', LLMModel) { }

@Resolver(() => LLMModel)
export class LLMModelResolverBase extends BaseResolver {
  protected getRepository(ctx: GraphQLContext): CustomRepository<LLMModel> {
    // Entity has userId field - use ownership-aware repository with context
    return this.getOwnedRepository(LLMModel, ctx);
  }

  protected get repository(): RelayRepository<LLMModel> {
    // This getter is for backward compatibility - use getRepository(ctx) in new methods
    throw new Error('Use getRepository(ctx) instead of this.repository to provide user context');
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Fetch single LLMModel by ID
   */
  @Query(() => LLMModel, { nullable: true, description: 'Fetch LLMModel by ID' })
  async lLMModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<LLMModel | null> {
    return await this.getRepository(ctx).findOne({ where: { id: id } });
  }

  /**
   * Fetch LLMModel collection (Relay connection)
   */
  @Query(() => LLMModelConnection, { description: 'Fetch LLMModel collection (paginated)' })
  async lLMModels(
    @Args(() => ConnectionArgs) args: ConnectionArgs,
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<ReturnType<typeof connectionFromArray<LLMModel>>> {
    const where = kind === 'default' ? { deletedAt: IsNull() } : {};
    const [items, totalCount] = await this.getRepository(ctx).findAndCount({ where });
    return connectionFromArray(items, args, totalCount);
  }

  /**
   * Fetch LLMModel array (non-paginated)
   */
  @Query(() => [LLMModel], { description: 'Fetch LLMModel array' })
  async lLMModelsArray(
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<LLMModel[]> {
    if (kind === 'all') {
      return await this.getRepository(ctx).find({ withDeleted: true });
    }
    return await this.getRepository(ctx).find();
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Create new LLMModel
   */
  @FieldMutation(CreateLLMModelInput, LLMModel, {
    description: 'Create new LLMModel'
  })
  async createLLMModel(
    input: CreateLLMModelInput,
    ctx: GraphQLContext
  ): Promise<LLMModel> {
    const entity = this.getRepository(ctx).create(input);
    // Auto-attach userId directly to entity (preserve constructor)
    if (ctx.user) {
      (entity).userId = ctx.user?.id;
    }
    return await this.getRepository(ctx).save(entity);
  }

  /**
   * Update existing LLMModel
   */
  @FieldMutation(UpdateLLMModelInput, LLMModel, {
    description: 'Update existing LLMModel'
  })
  async updateLLMModel(
    input: UpdateLLMModelInput,
    ctx: GraphQLContext
  ): Promise<LLMModel> {
    // Create update data object, excluding protected fields and undefined values
    const updateData: any = {};
    const excludeFields = ['id', 'userId'];

    for (const [key, value] of Object.entries(input)) {
      if (!excludeFields.includes(key) && value !== undefined) {
        updateData[key] = value;
      }
    }

    // Use the repository's updateById method which works properly with TypeORM
    return await this.getRepository(ctx).updateById(input.id, updateData);
  }

  /**
   * Create or update LLMModel (upsert)
   */
  @FieldMutation(CreateUpdateLLMModelInput, LLMModel, {
    description: 'Create or update LLMModel'
  })
  async createUpdateLLMModel(
    input: CreateUpdateLLMModelInput,
    ctx: GraphQLContext
  ): Promise<LLMModel> {
    if (input.id) {
      // Update existing

      // Create update data object, excluding protected fields and undefined values
      const updateData: any = {};
      const excludeFields = ['id', 'userId'];

      for (const [key, value] of Object.entries(input)) {
        if (!excludeFields.includes(key) && value !== undefined) {
          updateData[key] = value;
        }
      }

      // Use the repository's updateById method which works properly with TypeORM
      return await this.getRepository(ctx).updateById(input.id, updateData);
    } else {
      // Create new
      const { id, ...createData } = input;
      const entity = this.getRepository(ctx).create(createData);
      // Auto-attach userId directly to entity (preserve constructor)
      if (ctx.user) {
        (entity).userId = ctx.user?.id;
      }
      return await this.getRepository(ctx).save(entity);
    }
  }

  /**
   * Soft delete LLMModel
   */
  @Mutation(() => Boolean, { description: 'Soft delete LLMModel' })
  async destroyLLMModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    // Use the repository's softDeleteById method which handles ownership and already-deleted entities
    await this.getRepository(ctx).softDeleteById(id);
    return true;
  }

  /**
   * Hard delete LLMModel
   */
  @Mutation(() => Boolean, { description: 'Hard delete LLMModel (permanent)' })
  async deleteLLMModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: id } });


    await this.getRepository(ctx).hardDeleteById(id);
    return true;
  }

  /**
   * Restore soft-deleted LLMModel
   */
  @Mutation(() => LLMModel, { nullable: true, description: 'Restore soft-deleted LLMModel' })
  async restoreLLMModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<LLMModel | null> {
    const entity = await this.getRepository(ctx).findOne({
      where: { id: id },
      withDeleted: true
    });

    if (!entity || !entity.deletedAt) {
      return null;
    }


    return await this.getRepository(ctx).recoverById(id);
  }
}
