/**
 * LLMModelResolver - Generated GraphQL resolver
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/LLMModel.json
 *
 * To customize:
 * 1. Extend this class in main/graphql/resolvers/LLMModelResolver.ts
 * 2. Override methods as needed
 *
 */

import { Resolver, Query, Mutation, Arg, Ctx, Args, ObjectType } from 'type-graphql';
import { IsNull } from 'typeorm';
import { LLMModel } from '@db/entities/LLMModel.js';
import { CreateLLMModelInput } from '@main/graphql/inputs/LLMModelInputs.js';
import { CreateUpdateLLMModelInput } from '@main/graphql/inputs/LLMModelInputs.js';
import { UpdateLLMModelInput } from '@main/graphql/inputs/LLMModelInputs.js';
import type { GraphQLContext } from '@shared/types';
import { connectionFromArray, RelayRepository, fromGlobalIdToLocalId } from '@base/graphql/index.js';
import { createConnectionType, ConnectionArgs } from '@base/graphql/relay/Connection.js';
import { BaseResolver } from '@base/graphql/BaseResolver.js';

@ObjectType()
export class LLMModelConnection extends createConnectionType('LLMModel', LLMModel) { }

@Resolver(() => LLMModel)
export class LLMModelResolverBase extends BaseResolver {
  protected getRepository(ctx: GraphQLContext): RelayRepository<LLMModel> {
    // Entity has userId field - use ownership-aware repository with context
    return this.getRelayRepository(LLMModel, ctx);
  }

  protected get repository(): RelayRepository<LLMModel> {
    // This getter is for backward compatibility - use getRepository(ctx) in new methods
    throw new Error('Use getRepository(ctx) instead of this.repository to provide user context');
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Fetch single LLMModel by ID
   */
  @Query(() => LLMModel, { nullable: true, description: 'Fetch LLMModel by ID' })
  async lLMModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<LLMModel | null> {
    const localId = fromGlobalIdToLocalId(id);
    return await this.getRepository(ctx).findOne({ where: { id: localId } });
  }

  /**
   * Fetch LLMModel collection (Relay connection)
   */
  @Query(() => LLMModelConnection, { description: 'Fetch LLMModel collection (paginated)' })
  async lLMModels(
    @Args(() => ConnectionArgs) args: ConnectionArgs,
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<ReturnType<typeof connectionFromArray<LLMModel>>> {
    const where = kind === 'default' ? { deletedAt: IsNull() } : {};
    const [items, totalCount] = await this.getRepository(ctx).findAndCount({ where });
    return connectionFromArray(items, args, totalCount);
  }

  /**
   * Fetch LLMModel array (non-paginated)
   */
  @Query(() => [LLMModel], { description: 'Fetch LLMModel array' })
  async lLMModelsArray(
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<LLMModel[]> {
    if (kind === 'all') {
      return await this.getRepository(ctx).find({ withDeleted: true });
    }
    return await this.getRepository(ctx).find();
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Create new LLMModel
   */
  @Mutation(() => LLMModel, { description: 'Create new LLMModel' })
  async createLLMModel(
    @Arg('input', () => CreateLLMModelInput) input: CreateLLMModelInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<LLMModel> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    const entity = this.getRepository(ctx).create(input as any);
    // Auto-attach userId directly to entity (preserve constructor)
    (entity as any).userId = ctx.user?.id;
    return await this.getRepository(ctx).save(entity as any);
  }

  /**
   * Update existing LLMModel
   */
  @Mutation(() => LLMModel, { description: 'Update existing LLMModel' })
  async updateLLMModel(
    @Arg('input', () => UpdateLLMModelInput) input: UpdateLLMModelInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<LLMModel> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: fromGlobalIdToLocalId(input.id) } });

    // Safely assign only defined, updatable fields (excludes id, userId and undefined values)
    this.safeAssignUpdate(entity, input);
    return await this.getRepository(ctx).save(entity as any);
  }

  /**
   * Create or update LLMModel (upsert)
   */
  @Mutation(() => LLMModel, { description: 'Create or update LLMModel' })
  async createUpdateLLMModel(
    @Arg('input', () => CreateUpdateLLMModelInput) input: CreateUpdateLLMModelInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<LLMModel> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    if (input.id) {
      // Update existing
      const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: fromGlobalIdToLocalId(input.id) } });

      // Safely assign only defined, updatable fields (excludes id, userId and undefined values)
      this.safeAssignUpdate(entity, input);
      return await this.getRepository(ctx).save(entity as any);
    } else {
      // Create new
      const { id, ...createData } = input;
      const entity = this.getRepository(ctx).create(createData as any);
      // Auto-attach userId directly to entity (preserve constructor)
      (entity as any).userId = ctx.user?.id;
      return await this.getRepository(ctx).save(entity as any);
    }
  }

  /**
   * Soft delete LLMModel
   */
  @Mutation(() => Boolean, { description: 'Soft delete LLMModel' })
  async destroyLLMModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    // Use the repository's softDeleteById method which handles ownership and already-deleted entities
    const localId = fromGlobalIdToLocalId(id);
    await this.getRepository(ctx).softDeleteById(localId);
    return true;
  }

  /**
   * Hard delete LLMModel
   */
  @Mutation(() => Boolean, { description: 'Hard delete LLMModel (permanent)' })
  async deleteLLMModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: localId } });


    await this.getRepository(ctx).hardDeleteById(localId);
    return true;
  }

  /**
   * Restore soft-deleted LLMModel
   */
  @Mutation(() => LLMModel, { nullable: true, description: 'Restore soft-deleted LLMModel' })
  async restoreLLMModel(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<LLMModel | null> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOne({
      where: { id: localId },
      withDeleted: true
    });

    if (!entity || !entity.deletedAt) {
      return null;
    }


    return await this.getRepository(ctx).recoverById(localId);
  }
}
