/**
 * MessageVersionResolver - Generated GraphQL resolver
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/MessageVersion.json
 *
 * To customize:
 * 1. Extend this class in main/graphql/resolvers/MessageVersionResolver.ts
 * 2. Override methods as needed
 *
 */

import { Resolver, Query, Mutation, Arg, Ctx, Args, ObjectType } from 'type-graphql';
import { IsNull } from 'typeorm';
import { MessageVersion } from '@db/entities/MessageVersion.js';
import { CreateMessageVersionInput } from '@main/graphql/inputs/MessageVersionInputs.js';
import { CreateUpdateMessageVersionInput } from '@main/graphql/inputs/MessageVersionInputs.js';
import { UpdateMessageVersionInput } from '@main/graphql/inputs/MessageVersionInputs.js';
import type { GraphQLContext } from '@shared/types';
import { connectionFromArray, RelayRepository, fromGlobalIdToLocalId } from '@base/graphql/index.js';
import { createConnectionType, ConnectionArgs } from '@base/graphql/relay/Connection.js';
import { BaseResolver } from '@base/graphql/BaseResolver.js';

@ObjectType()
export class MessageVersionConnection extends createConnectionType('MessageVersion', MessageVersion) { }

@Resolver(() => MessageVersion)
export class MessageVersionResolverBase extends BaseResolver {
  protected getRepository(ctx: GraphQLContext): RelayRepository<MessageVersion> {
    // Entity has userId field - use ownership-aware repository with context
    return this.getRelayRepository(MessageVersion, ctx);
  }

  protected get repository(): RelayRepository<MessageVersion> {
    // This getter is for backward compatibility - use getRepository(ctx) in new methods
    throw new Error('Use getRepository(ctx) instead of this.repository to provide user context');
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Fetch single MessageVersion by ID
   */
  @Query(() => MessageVersion, { nullable: true, description: 'Fetch MessageVersion by ID' })
  async messageVersion(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<MessageVersion | null> {
    const localId = fromGlobalIdToLocalId(id);
    return await this.getRepository(ctx).findOne({ where: { id: localId } });
  }

  /**
   * Fetch MessageVersion collection (Relay connection)
   */
  @Query(() => MessageVersionConnection, { description: 'Fetch MessageVersion collection (paginated)' })
  async messageVersions(
    @Args(() => ConnectionArgs) args: ConnectionArgs,
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<ReturnType<typeof connectionFromArray<MessageVersion>>> {
    const where = kind === 'default' ? { deletedAt: IsNull() } : {};
    const [items, totalCount] = await this.getRepository(ctx).findAndCount({ where });
    return connectionFromArray(items, args, totalCount);
  }

  /**
   * Fetch MessageVersion array (non-paginated)
   */
  @Query(() => [MessageVersion], { description: 'Fetch MessageVersion array' })
  async messageVersionsArray(
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<MessageVersion[]> {
    if (kind === 'all') {
      return await this.getRepository(ctx).find({ withDeleted: true });
    }
    return await this.getRepository(ctx).find();
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Create new MessageVersion
   */
  @Mutation(() => MessageVersion, { description: 'Create new MessageVersion' })
  async createMessageVersion(
    @Arg('input', () => CreateMessageVersionInput) input: CreateMessageVersionInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<MessageVersion> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    const entity = this.getRepository(ctx).create(input as any);
    // Auto-attach userId directly to entity (preserve constructor)
    (entity as any).userId = ctx.user?.id;
    return await this.getRepository(ctx).save(entity as any);
  }

  /**
   * Update existing MessageVersion
   */
  @Mutation(() => MessageVersion, { description: 'Update existing MessageVersion' })
  async updateMessageVersion(
    @Arg('input', () => UpdateMessageVersionInput) input: UpdateMessageVersionInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<MessageVersion> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: fromGlobalIdToLocalId(input.id) } });

    // Safely assign only defined, updatable fields (excludes id, userId and undefined values)
    this.safeAssignUpdate(entity, input);
    return await this.getRepository(ctx).save(entity as any);
  }

  /**
   * Create or update MessageVersion (upsert)
   */
  @Mutation(() => MessageVersion, { description: 'Create or update MessageVersion' })
  async createUpdateMessageVersion(
    @Arg('input', () => CreateUpdateMessageVersionInput) input: CreateUpdateMessageVersionInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<MessageVersion> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    if (input.id) {
      // Update existing
      const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: fromGlobalIdToLocalId(input.id) } });

      // Safely assign only defined, updatable fields (excludes id, userId and undefined values)
      this.safeAssignUpdate(entity, input);
      return await this.getRepository(ctx).save(entity as any);
    } else {
      // Create new
      const { id, ...createData } = input;
      const entity = this.getRepository(ctx).create(createData as any);
      // Auto-attach userId directly to entity (preserve constructor)
      (entity as any).userId = ctx.user?.id;
      return await this.getRepository(ctx).save(entity as any);
    }
  }

  /**
   * Soft delete MessageVersion
   */
  @Mutation(() => Boolean, { description: 'Soft delete MessageVersion' })
  async destroyMessageVersion(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    // Use the repository's softDeleteById method which handles ownership and already-deleted entities
    const localId = fromGlobalIdToLocalId(id);
    await this.getRepository(ctx).softDeleteById(localId);
    return true;
  }

  /**
   * Hard delete MessageVersion
   */
  @Mutation(() => Boolean, { description: 'Hard delete MessageVersion (permanent)' })
  async deleteMessageVersion(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: localId } });


    await this.getRepository(ctx).hardDeleteById(localId);
    return true;
  }

  /**
   * Restore soft-deleted MessageVersion
   */
  @Mutation(() => MessageVersion, { nullable: true, description: 'Restore soft-deleted MessageVersion' })
  async restoreMessageVersion(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<MessageVersion | null> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOne({
      where: { id: localId },
      withDeleted: true
    });

    if (!entity || !entity.deletedAt) {
      return null;
    }


    return await this.getRepository(ctx).recoverById(localId);
  }
}
