/**
 * MessageResolver - Generated GraphQL resolver
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/Message.json
 *
 * To customize:
 * 1. Extend this class in main/graphql/resolvers/MessageResolver.ts
 * 2. Override methods as needed
 *
 */

import { Resolver, Query, Mutation, Arg, Ctx, Args, ObjectType } from 'type-graphql';
import { IsNull } from 'typeorm';
import { Message } from '@db/entities/Message.js';
import { UpdateMessageInput } from '@main/graphql/inputs/MessageInputs.js';
import type { GraphQLContext } from '@shared/types';
import { connectionFromArray, RelayRepository, fromGlobalIdToLocalId } from '@base/graphql/index.js';
import { createConnectionType, ConnectionArgs } from '@base/graphql/relay/Connection.js';
import { BaseResolver } from '@base/graphql/BaseResolver.js';

@ObjectType()
export class MessageConnection extends createConnectionType('Message', Message) { }

@Resolver(() => Message)
export class MessageResolverBase extends BaseResolver {
  protected getRepository(ctx: GraphQLContext): RelayRepository<Message> {
    // Entity has userId field - use ownership-aware repository with context
    return this.getRelayRepository(Message, ctx);
  }

  protected get repository(): RelayRepository<Message> {
    // This getter is for backward compatibility - use getRepository(ctx) in new methods
    throw new Error('Use getRepository(ctx) instead of this.repository to provide user context');
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Fetch single Message by ID
   */
  @Query(() => Message, { nullable: true, description: 'Fetch Message by ID' })
  async message(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<Message | null> {
    const localId = fromGlobalIdToLocalId(id);
    return await this.getRepository(ctx).findOne({ where: { id: localId } });
  }

  /**
   * Fetch Message collection (Relay connection)
   */
  @Query(() => MessageConnection, { description: 'Fetch Message collection (paginated)' })
  async messages(
    @Args(() => ConnectionArgs) args: ConnectionArgs,
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<ReturnType<typeof connectionFromArray<Message>>> {
    const where = kind === 'default' ? { deletedAt: IsNull() } : {};
    const [items, totalCount] = await this.getRepository(ctx).findAndCount({ where });
    return connectionFromArray(items, args, totalCount);
  }

  /**
   * Fetch Message array (non-paginated)
   */
  @Query(() => [Message], { description: 'Fetch Message array' })
  async messagesArray(
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<Message[]> {
    if (kind === 'all') {
      return await this.getRepository(ctx).find({ withDeleted: true });
    }
    return await this.getRepository(ctx).find();
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────


  /**
   * Update existing Message
   */
  @Mutation(() => Message, { description: 'Update existing Message' })
  async updateMessage(
    @Arg('input', () => UpdateMessageInput) input: UpdateMessageInput,
    @Ctx() ctx: GraphQLContext
  ): Promise<Message> {
    // Validate input using class-validator
    input = await this.validateInput(input);

    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: fromGlobalIdToLocalId(input.id) } });

    // Safely assign only defined, updatable fields (excludes id, userId and undefined values)
    this.safeAssignUpdate(entity, input);
    return await this.getRepository(ctx).save(entity as any);
  }


  /**
   * Soft delete Message
   */
  @Mutation(() => Boolean, { description: 'Soft delete Message' })
  async destroyMessage(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    // Use the repository's softDeleteById method which handles ownership and already-deleted entities
    const localId = fromGlobalIdToLocalId(id);
    await this.getRepository(ctx).softDeleteById(localId);
    return true;
  }

  /**
   * Hard delete Message
   */
  @Mutation(() => Boolean, { description: 'Hard delete Message (permanent)' })
  async deleteMessage(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: localId } });


    await this.getRepository(ctx).hardDeleteById(localId);
    return true;
  }

  /**
   * Restore soft-deleted Message
   */
  @Mutation(() => Message, { nullable: true, description: 'Restore soft-deleted Message' })
  async restoreMessage(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<Message | null> {
    const localId = fromGlobalIdToLocalId(id);
    const entity = await this.getRepository(ctx).findOne({
      where: { id: localId },
      withDeleted: true
    });

    if (!entity || !entity.deletedAt) {
      return null;
    }


    return await this.getRepository(ctx).recoverById(localId);
  }
}
