/**
 * MessageVersionResolver - Generated GraphQL resolver
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/MessageVersion.json
 *
 * To customize:
 * 1. Extend this class in main/graphql/resolvers/MessageVersionResolver.ts
 * 2. Override methods as needed
 *
 */

import { Resolver, Query, Mutation, Arg, Ctx, Args, ObjectType } from 'type-graphql';
import { IsNull } from 'typeorm';
import { MessageVersion } from '@db/entities/MessageVersion.js';
import { CreateMessageVersionInput } from '@main/graphql/inputs/MessageVersionInputs.js';
import { CreateUpdateMessageVersionInput } from '@main/graphql/inputs/MessageVersionInputs.js';
import { UpdateMessageVersionInput } from '@main/graphql/inputs/MessageVersionInputs.js';
import type { GraphQLContext } from '@shared/types';
import { connectionFromArray, RelayRepository, fromGlobalIdToLocalId, FieldMutation, CustomRepository } from '@base/graphql/index.js';
import { createConnectionType, ConnectionArgs } from '@base/graphql/relay/Connection.js';
import { BaseResolver } from '@base/graphql/BaseResolver.js';

@ObjectType()
export class MessageVersionConnection extends createConnectionType('MessageVersion', MessageVersion) { }

@Resolver(() => MessageVersion)
export class MessageVersionResolverBase extends BaseResolver {
  protected getRepository(ctx: GraphQLContext): CustomRepository<MessageVersion> {
    // Entity has userId field - use ownership-aware repository with context
    return this.getOwnedRepository(MessageVersion, ctx);
  }

  protected get repository(): RelayRepository<MessageVersion> {
    // This getter is for backward compatibility - use getRepository(ctx) in new methods
    throw new Error('Use getRepository(ctx) instead of this.repository to provide user context');
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Fetch single MessageVersion by ID
   */
  @Query(() => MessageVersion, { nullable: true, description: 'Fetch MessageVersion by ID' })
  async messageVersion(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<MessageVersion | null> {
    return await this.getRepository(ctx).findOne({ where: { id: id } });
  }

  /**
   * Fetch MessageVersion collection (Relay connection)
   */
  @Query(() => MessageVersionConnection, { description: 'Fetch MessageVersion collection (paginated)' })
  async messageVersions(
    @Args(() => ConnectionArgs) args: ConnectionArgs,
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<ReturnType<typeof connectionFromArray<MessageVersion>>> {
    const where = kind === 'default' ? { deletedAt: IsNull() } : {};
    const [items, totalCount] = await this.getRepository(ctx).findAndCount({ where });
    return connectionFromArray(items, args, totalCount);
  }

  /**
   * Fetch MessageVersion array (non-paginated)
   */
  @Query(() => [MessageVersion], { description: 'Fetch MessageVersion array' })
  async messageVersionsArray(
    @Arg('kind', () => String, { defaultValue: 'default' }) kind: 'default' | 'all',
    @Ctx() ctx: GraphQLContext
  ): Promise<MessageVersion[]> {
    if (kind === 'all') {
      return await this.getRepository(ctx).find({ withDeleted: true });
    }
    return await this.getRepository(ctx).find();
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Create new MessageVersion
   */
  @FieldMutation(CreateMessageVersionInput, MessageVersion, {
    description: 'Create new MessageVersion'
  })
  async createMessageVersion(
    input: CreateMessageVersionInput,
    ctx: GraphQLContext
  ): Promise<MessageVersion> {
    const entity = this.getRepository(ctx).create(input);
    // Auto-attach userId directly to entity (preserve constructor)
    if (ctx.user) {
      (entity).userId = ctx.user?.id;
    }
    return await this.getRepository(ctx).save(entity);
  }

  /**
   * Update existing MessageVersion
   */
  @FieldMutation(UpdateMessageVersionInput, MessageVersion, {
    description: 'Update existing MessageVersion'
  })
  async updateMessageVersion(
    input: UpdateMessageVersionInput,
    ctx: GraphQLContext
  ): Promise<MessageVersion> {
    // Create update data object, excluding protected fields and undefined values
    const updateData: any = {};
    const excludeFields = ['id', 'userId'];

    for (const [key, value] of Object.entries(input)) {
      if (!excludeFields.includes(key) && value !== undefined) {
        updateData[key] = value;
      }
    }

    // Use the repository's updateById method which works properly with TypeORM
    return await this.getRepository(ctx).updateById(input.id, updateData);
  }

  /**
   * Create or update MessageVersion (upsert)
   */
  @FieldMutation(CreateUpdateMessageVersionInput, MessageVersion, {
    description: 'Create or update MessageVersion'
  })
  async createUpdateMessageVersion(
    input: CreateUpdateMessageVersionInput,
    ctx: GraphQLContext
  ): Promise<MessageVersion> {
    if (input.id) {
      // Update existing

      // Create update data object, excluding protected fields and undefined values
      const updateData: any = {};
      const excludeFields = ['id', 'userId'];

      for (const [key, value] of Object.entries(input)) {
        if (!excludeFields.includes(key) && value !== undefined) {
          updateData[key] = value;
        }
      }

      // Use the repository's updateById method which works properly with TypeORM
      return await this.getRepository(ctx).updateById(input.id, updateData);
    } else {
      // Create new
      const { id, ...createData } = input;
      const entity = this.getRepository(ctx).create(createData);
      // Auto-attach userId directly to entity (preserve constructor)
      if (ctx.user) {
        (entity).userId = ctx.user?.id;
      }
      return await this.getRepository(ctx).save(entity);
    }
  }

  /**
   * Soft delete MessageVersion
   */
  @Mutation(() => Boolean, { description: 'Soft delete MessageVersion' })
  async destroyMessageVersion(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    // Use the repository's softDeleteById method which handles ownership and already-deleted entities
    await this.getRepository(ctx).softDeleteById(id);
    return true;
  }

  /**
   * Hard delete MessageVersion
   */
  @Mutation(() => Boolean, { description: 'Hard delete MessageVersion (permanent)' })
  async deleteMessageVersion(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<boolean> {
    const entity = await this.getRepository(ctx).findOneOrFail({ where: { id: id } });


    await this.getRepository(ctx).hardDeleteById(id);
    return true;
  }

  /**
   * Restore soft-deleted MessageVersion
   */
  @Mutation(() => MessageVersion, { nullable: true, description: 'Restore soft-deleted MessageVersion' })
  async restoreMessageVersion(
    @Arg('id', () => String) id: string,
    @Ctx() ctx: GraphQLContext
  ): Promise<MessageVersion | null> {
    const entity = await this.getRepository(ctx).findOne({
      where: { id: id },
      withDeleted: true
    });

    if (!entity || !entity.deletedAt) {
      return null;
    }


    return await this.getRepository(ctx).recoverById(id);
  }
}
