/**
 * Resolver Paths - Centralized Resolver Import Paths
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is auto-generated from schemas/*.json and resolvers/
 *
 * Purpose: Single source of truth for all resolver imports with static loading.
 * Simplified approach that directly imports all resolver classes for better performance
 * and type safety without the complexity of dynamic loading.
 *
 * Benefits:
 * - Static: All imports resolved at compile time
 * - Type-safe: Direct TypeScript imports
 * - Simple: No dynamic loading complexity
 * - Performant: No runtime import overhead
 */

// Base resolvers
import { UserResolver } from '@main/base/graphql/UserResolver.js';
import { NodeResolver, NodeFieldResolver } from '@base/graphql/index.js';

// Domain resolvers
import { ChatResolver } from './resolvers/ChatResolver';
import { ConnectionResolver } from './resolvers/ConnectionResolver';
import { EmbeddingModelResolver } from './resolvers/EmbeddingModelResolver';
import { FileResolver } from './resolvers/FileResolver';
import { LLMModelResolver } from './resolvers/LLMModelResolver';
import { MessageResolver } from './resolvers/MessageResolver';
import { MessageVersionResolver } from './resolvers/MessageVersionResolver';

/**
 * Static resolver classes object
 *
 * Provides direct access to all resolver classes without dynamic loading.
 * This is the preferred way to access resolvers in the application.
 */
export const resolverClasses = {
  UserResolver,
  NodeResolver,
  NodeFieldResolver,
  ChatResolver,
  ConnectionResolver,
  EmbeddingModelResolver,
  FileResolver,
  LLMModelResolver,
  MessageResolver,
  MessageVersionResolver,
} as const;

/**
 * Type definition for resolver name keys
 */
export type ResolverName = keyof typeof resolverClasses;

/**
 * Type for all resolver classes
 */
export type ResolverClasses = typeof resolverClasses;

/**
 * Get a specific resolver class by name
 *
 * @param name - Resolver name
 * @returns Resolver class
 *
 * @example
 * ```typescript
 * const UserResolver = getResolverClass('UserResolver');
 * ```
 */
export function getResolverClass<K extends ResolverName>(name: K): ResolverClasses[K] {
  return resolverClasses[name];
}

/**
 * Get all resolver classes as an object
 *
 * @returns All resolver classes
 *
 * @example
 * ```typescript
 * const resolvers = getAllResolverClasses();
 * const { UserResolver, ChatResolver } = resolvers;
 * ```
 */
export function getAllResolverClasses(): ResolverClasses {
  return resolverClasses;
}

/**
 * Get all resolver classes as an array
 *
 * Useful for TypeGraphQL schema building and other contexts
 * that expect an array of resolver classes.
 *
 * @returns Array of all resolver classes
 *
 * @example
 * ```typescript
 * const resolvers = getResolverClassesArray();
 * const schema = await buildSchema({ resolvers });
 * ```
 */
// eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
export function getResolverClassesArray(): Function[] {
  return Object.values(resolverClasses);
}

/**
 * Get all resolver names as an array
 *
 * @returns Array of all resolver names
 *
 * @example
 * ```typescript
 * const allNames = getAllResolverNames(); // ['UserResolver', 'ChatResolver', ...]
 * ```
 */
export function getAllResolverNames(): ResolverName[] {
  return Object.keys(resolverClasses) as ResolverName[];
}

/**
 * Get resolvers as array for TypeGraphQL schema (legacy compatibility)
 *
 * Maintains backward compatibility with the old async API.
 * Now simply returns the static resolvers wrapped in a Promise.
 *
 * @returns Promise resolving to array of resolver classes
 *
 * @example
 * ```typescript
 * const resolverClasses = await getResolverClassesAsync();
 * ```
 */
// eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
export async function getResolverClasses(): Promise<Function[]> {
  return getResolverClassesArray();
}